ALTER TABLE devices ADD COLUMN `defaultuser` varchar(100) DEFAULT NULL;
ALTER TABLE devices MODIFY COLUMN defaultuser varchar(100);
ALTER TABLE devices ADD COLUMN `useragent` varchar(20) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `type` enum('friend','user','peer') DEFAULT 'friend';
ALTER TABLE devices ADD COLUMN `md5secret` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `remotesecret` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `transport` enum('udp','tcp','udp,tcp','tcp,udp') DEFAULT 'udp';
ALTER TABLE devices ADD COLUMN `directmedia` enum('yes','no','nonat','update') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `useclientcode` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `setvar` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `amaflags` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `callcounter` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `busylevel` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `allowoverlap` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `allowsubscribe` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `maxcallbitrate` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `rfc2833compensate` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `session-timers` enum('accept','refuse','originate') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `session-expires` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `session-minse` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `session-refresher` enum('uac','uas') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `t38pt_usertpsource` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `regexten` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `defaultip` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `rtptimeout` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `rtpholdtimeout` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `outboundproxy` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `callbackextension` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `timert1` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `timerb` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `qualifyfreq` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `constantssrc` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `contactpermit` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `contactdeny` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `usereqphone` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `textsupport` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `faxdetect` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `buggymwi` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `auth` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `fullname` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `trunkname` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `cid_number` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `callingpres` enum('allowed_not_screened','allowed_passed_screen','allowed_failed_screen','allowed','prohib_not_screened','prohib_passed_screen',  'prohib_failed_screen','prohib') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `mohinterpret` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `mohsuggest` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `parkinglot` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `hasvoicemail` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `subscribemwi` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `vmexten` varchar(40) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `autoframing` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `rtpkeepalive` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `call-limit` int(11) DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `g726nonstandard` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `ignoresdpversion` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `allowtransfer` enum('yes','no') DEFAULT NULL;
ALTER TABLE devices ADD COLUMN `dynamic` enum('yes','no') DEFAULT NULL;
CREATE INDEX `ipaddr` ON devices(ipaddr, port);
CREATE INDEX `host` ON devices(host, port);
DROP INDEX `id` ON devices;
UPDATE devices SET type = 'friend';
UPDATE devices SET `transport` = 'udp' where transport not in ('udp','tcp','udp,tcp','tcp,udp','tls');
UPDATE extlines SET appdata=( REPLACE (appdata,'|', ',')) where appdata not like "$[$[%${DIALSTATUS%CHANUNAVAIL%]|$[%DIALSTATUS%CONGESTION%";
UPDATE extlines SET appdata=( REPLACE (appdata,'],$[', ']|$['));
UPDATE devices SET defaultuser = username;
DROP TRIGGER `defuser`;
## SQL sentences goes to the top ^^^^^ from this line
# make sure you press ENTER (to end line) after last SQL sentence!
# also whole SQL sentence should go into one line
# ------------ DO NOT WRITE NOTHING PAST THIS LINE ---------------