#!/usr/bin/env bash

if [[ -s "/usr/local/rvm/environments/ruby-1.9.3-p327@x4" ]]
then
  source "/usr/local/rvm/environments/ruby-1.9.3-p327@x4"
  exec ruby "$@"
else
  echo "ERROR: Missing RVM environment file: '/usr/local/rvm/environments/ruby-1.9.3-p327@x4'" >&2
  exit 1
fi
