
CREATE DATABASE mor CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON mor.* TO mor@localhost IDENTIFIED BY "mor" WITH GRANT OPTION;
GRANT PROCESS, SUPER, FILE, REPLICATION SLAVE , REPLICATION CLIENT ON * . * TO 'mor'@'localhost';

GRANT ALL PRIVILEGES ON mor.* TO mor@127.0.0.1 IDENTIFIED BY "mor" WITH GRANT OPTION;
GRANT PROCESS, SUPER, FILE, REPLICATION SLAVE , REPLICATION CLIENT ON * . * TO 'mor'@'127.0.0.1';

USE mor;
