# removing the mark that DB is updated from script
DELETE FROM conflines WHERE name = 'DB_Update_From_Script';

# DATA
UPDATE conflines SET value = 'MOR X4' WHERE value IN ('MOR 10', 'MOR 9', 'MOR 0.8', 'MOR 11', 'MOR 12', 'MOR X3') AND name IN ('Version', 'Admin_browser_Title');
UPDATE devices SET proxy_port = IF((SELECT value FROM conflines WHERE name='Proxy_port_first_load') = 1 , proxy_port, port);
INSERT IGNORE INTO conflines(name, value, owner_id) SELECT 'Proxy_port_first_load', '1', '0' FROM DUAL WHERE (SELECT COUNT(*) FROM conflines WHERE name = 'Proxy_port_first_load' AND owner_id = 0) = 0;
INSERT IGNORE INTO acc_rights (name, nice_name, permission_group, right_type) VALUES ('manage_queues', 'Manage_Queues', 'DID', 'accountant');
INSERT IGNORE INTO acc_rights (name, nice_name, permission_group, right_type) VALUES ("autodialer","Autodialer","Plugins","reseller");
INSERT IGNORE INTO acc_rights (name, nice_name, permission_group, right_type) VALUES ("recordings_manage","Manage_Recordings","Device","accountant");
update emails set body = "Monitoring details:\n\nType: <%=monitoring_type%>\nBalance: <%=monitoring_amount%>\nBlock: <%=monitoring_block%>\n\nAffected users:\n\n<%=monitoring_users%>\n<%= call_list %>" where body = "Monitoring details:nnType: <%=monitoring_type%>nBalance: <%=monitoring_amount%>nBlock: <%=monitoring_block%>nnAffected users:nn<%=monitoring_users%>n<%= call_list %>" and name = "monitoring_activation";
UPDATE conflines SET value = ' by <a href="http://www.kolmisoft.com" target="_blank">Kolmisoft </a> 2006 - <span id="current_year"></span><script type="text/javascript"> document.getElementById("current_year").innerHTML = new Date().getFullYear(); </script>' WHERE value like '%KolmiSoft%' and name = 'Copyright_Title';
INSERT IGNORE INTO conflines (name, value) SELECT 'Callback_legA_CID','device' FROM dual WHERE NOT EXISTS (SELECT * FROM conflines WHERE name='Callback_legA_CID');
INSERT IGNORE INTO conflines (name, value) SELECT 'Callback_legB_CID','device' FROM dual WHERE NOT EXISTS (SELECT * FROM conflines WHERE name='Callback_legB_CID');
INSERT IGNORE INTO bl_src_new_score (value, score) SELECT 'default','30' FROM dual WHERE NOT EXISTS (SELECT * FROM bl_src_new_score WHERE value='default');
INSERT IGNORE INTO bl_dst_new_score (value, score) SELECT 'default','30' FROM dual WHERE NOT EXISTS (SELECT * FROM bl_dst_new_score WHERE value='default');
INSERT IGNORE INTO bl_ip_new_score (value, score) SELECT 'default','30' FROM dual WHERE NOT EXISTS (SELECT * FROM bl_ip_new_score WHERE value='default');
UPDATE directions set iso31661code="004" WHERE id = 1;
UPDATE directions set iso31661code="008" WHERE id = 2;
UPDATE directions set iso31661code="012" WHERE id = 3;
UPDATE directions set iso31661code="016" WHERE id = 4;
UPDATE directions set iso31661code="020" WHERE id = 5;
UPDATE directions set iso31661code="024" WHERE id = 6;
UPDATE directions set iso31661code="660" WHERE id = 7;
UPDATE directions set iso31661code="010" WHERE id = 8;
UPDATE directions set iso31661code="028" WHERE id = 9;
UPDATE directions set iso31661code="032" WHERE id = 10;
UPDATE directions set iso31661code="051" WHERE id = 11;
UPDATE directions set iso31661code="533" WHERE id = 12;
UPDATE directions set iso31661code="036" WHERE id = 13;
UPDATE directions set iso31661code="040" WHERE id = 14;
UPDATE directions set iso31661code="031" WHERE id = 15;
UPDATE directions set iso31661code="044" WHERE id = 16;
UPDATE directions set iso31661code="048" WHERE id = 17;
UPDATE directions set iso31661code="050" WHERE id = 18;
UPDATE directions set iso31661code="052" WHERE id = 19;
UPDATE directions set iso31661code="112" WHERE id = 20;
UPDATE directions set iso31661code="056" WHERE id = 21;
UPDATE directions set iso31661code="084" WHERE id = 22;
UPDATE directions set iso31661code="204" WHERE id = 23;
UPDATE directions set iso31661code="060" WHERE id = 24;
UPDATE directions set iso31661code="064" WHERE id = 25;
UPDATE directions set iso31661code="068" WHERE id = 26;
UPDATE directions set iso31661code="070" WHERE id = 27;
UPDATE directions set iso31661code="072" WHERE id = 28;
UPDATE directions set iso31661code="076" WHERE id = 30;
UPDATE directions set iso31661code="096" WHERE id = 32;
UPDATE directions set iso31661code="100" WHERE id = 33;
UPDATE directions set iso31661code="854" WHERE id = 34;
UPDATE directions set iso31661code="108" WHERE id = 35;
UPDATE directions set iso31661code="116" WHERE id = 36;
UPDATE directions set iso31661code="120" WHERE id = 37;
UPDATE directions set iso31661code="124" WHERE id = 38;
UPDATE directions set iso31661code="132" WHERE id = 39;
UPDATE directions set iso31661code="136" WHERE id = 40;
UPDATE directions set iso31661code="140" WHERE id = 41;
UPDATE directions set iso31661code="148" WHERE id = 42;
UPDATE directions set iso31661code="152" WHERE id = 43;
UPDATE directions set iso31661code="156" WHERE id = 44;
UPDATE directions set iso31661code="162" WHERE id = 45;
UPDATE directions set iso31661code="166" WHERE id = 46;
UPDATE directions set iso31661code="170" WHERE id = 47;
UPDATE directions set iso31661code="174" WHERE id = 48;
UPDATE directions set iso31661code="178" WHERE id = 49;
UPDATE directions set iso31661code="180" WHERE id = 50;
UPDATE directions set iso31661code="184" WHERE id = 51;
UPDATE directions set iso31661code="188" WHERE id = 52;
UPDATE directions set iso31661code="384" WHERE id = 53;
UPDATE directions set iso31661code="191" WHERE id = 54;
UPDATE directions set iso31661code="192" WHERE id = 55;
UPDATE directions set iso31661code="196" WHERE id = 56;
UPDATE directions set iso31661code="203" WHERE id = 57;
UPDATE directions set iso31661code="208" WHERE id = 58;
UPDATE directions set iso31661code="262" WHERE id = 59;
UPDATE directions set iso31661code="212" WHERE id = 60;
UPDATE directions set iso31661code="214" WHERE id = 61;
UPDATE directions set iso31661code="218" WHERE id = 62;
UPDATE directions set iso31661code="818" WHERE id = 63;
UPDATE directions set iso31661code="222" WHERE id = 64;
UPDATE directions set iso31661code="226" WHERE id = 65;
UPDATE directions set iso31661code="232" WHERE id = 66;
UPDATE directions set iso31661code="233" WHERE id = 67;
UPDATE directions set iso31661code="231" WHERE id = 68;
UPDATE directions set iso31661code="238" WHERE id = 69;
UPDATE directions set iso31661code="234" WHERE id = 70;
UPDATE directions set iso31661code="242" WHERE id = 71;
UPDATE directions set iso31661code="246" WHERE id = 72;
UPDATE directions set iso31661code="250" WHERE id = 73;
UPDATE directions set iso31661code="254" WHERE id = 74;
UPDATE directions set iso31661code="258" WHERE id = 75;
UPDATE directions set iso31661code="266" WHERE id = 77;
UPDATE directions set iso31661code="270" WHERE id = 78;
UPDATE directions set iso31661code="268" WHERE id = 79;
UPDATE directions set iso31661code="276" WHERE id = 80;
UPDATE directions set iso31661code="288" WHERE id = 81;
UPDATE directions set iso31661code="292" WHERE id = 82;
UPDATE directions set iso31661code="300" WHERE id = 83;
UPDATE directions set iso31661code="304" WHERE id = 84;
UPDATE directions set iso31661code="308" WHERE id = 85;
UPDATE directions set iso31661code="312" WHERE id = 86;
UPDATE directions set iso31661code="316" WHERE id = 87;
UPDATE directions set iso31661code="320" WHERE id = 88;
UPDATE directions set iso31661code="324" WHERE id = 89;
UPDATE directions set iso31661code="624" WHERE id = 90;
UPDATE directions set iso31661code="328" WHERE id = 91;
UPDATE directions set iso31661code="332" WHERE id = 92;
UPDATE directions set iso31661code="336" WHERE id = 94;
UPDATE directions set iso31661code="340" WHERE id = 95;
UPDATE directions set iso31661code="344" WHERE id = 96;
UPDATE directions set iso31661code="348" WHERE id = 97;
UPDATE directions set iso31661code="352" WHERE id = 98;
UPDATE directions set iso31661code="356" WHERE id = 99;
UPDATE directions set iso31661code="360" WHERE id = 100;
UPDATE directions set iso31661code="364" WHERE id = 101;
UPDATE directions set iso31661code="368" WHERE id = 102;
UPDATE directions set iso31661code="372" WHERE id = 103;
UPDATE directions set iso31661code="376" WHERE id = 104;
UPDATE directions set iso31661code="380" WHERE id = 105;
UPDATE directions set iso31661code="388" WHERE id = 106;
UPDATE directions set iso31661code="392" WHERE id = 107;
UPDATE directions set iso31661code="400" WHERE id = 108;
UPDATE directions set iso31661code="398" WHERE id = 109;
UPDATE directions set iso31661code="404" WHERE id = 110;
UPDATE directions set iso31661code="296" WHERE id = 111;
UPDATE directions set iso31661code="408" WHERE id = 112;
UPDATE directions set iso31661code="410" WHERE id = 113;
UPDATE directions set iso31661code="414" WHERE id = 114;
UPDATE directions set iso31661code="417" WHERE id = 115;
UPDATE directions set iso31661code="418" WHERE id = 116;
UPDATE directions set iso31661code="428" WHERE id = 117;
UPDATE directions set iso31661code="422" WHERE id = 118;
UPDATE directions set iso31661code="426" WHERE id = 119;
UPDATE directions set iso31661code="430" WHERE id = 120;
UPDATE directions set iso31661code="434" WHERE id = 121;
UPDATE directions set iso31661code="438" WHERE id = 122;
UPDATE directions set iso31661code="440" WHERE id = 123;
UPDATE directions set iso31661code="442" WHERE id = 124;
UPDATE directions set iso31661code="446" WHERE id = 125;
UPDATE directions set iso31661code="807" WHERE id = 126;
UPDATE directions set iso31661code="450" WHERE id = 127;
UPDATE directions set iso31661code="454" WHERE id = 128;
UPDATE directions set iso31661code="458" WHERE id = 129;
UPDATE directions set iso31661code="462" WHERE id = 130;
UPDATE directions set iso31661code="466" WHERE id = 131;
UPDATE directions set iso31661code="470" WHERE id = 132;
UPDATE directions set iso31661code="584" WHERE id = 133;
UPDATE directions set iso31661code="474" WHERE id = 134;
UPDATE directions set iso31661code="478" WHERE id = 135;
UPDATE directions set iso31661code="480" WHERE id = 136;
UPDATE directions set iso31661code="175" WHERE id = 137;
UPDATE directions set iso31661code="484" WHERE id = 138;
UPDATE directions set iso31661code="583" WHERE id = 139;
UPDATE directions set iso31661code="498" WHERE id = 140;
UPDATE directions set iso31661code="492" WHERE id = 141;
UPDATE directions set iso31661code="496" WHERE id = 142;
UPDATE directions set iso31661code="500" WHERE id = 143;
UPDATE directions set iso31661code="504" WHERE id = 144;
UPDATE directions set iso31661code="508" WHERE id = 145;
UPDATE directions set iso31661code="104" WHERE id = 146;
UPDATE directions set iso31661code="516" WHERE id = 147;
UPDATE directions set iso31661code="520" WHERE id = 148;
UPDATE directions set iso31661code="524" WHERE id = 149;
UPDATE directions set iso31661code="528" WHERE id = 150;
UPDATE directions set iso31661code="530" WHERE id = 151;
UPDATE directions set iso31661code="540" WHERE id = 152;
UPDATE directions set iso31661code="554" WHERE id = 153;
UPDATE directions set iso31661code="558" WHERE id = 154;
UPDATE directions set iso31661code="562" WHERE id = 155;
UPDATE directions set iso31661code="566" WHERE id = 156;
UPDATE directions set iso31661code="570" WHERE id = 157;
UPDATE directions set iso31661code="574" WHERE id = 158;
UPDATE directions set iso31661code="580" WHERE id = 159;
UPDATE directions set iso31661code="578" WHERE id = 160;
UPDATE directions set iso31661code="512" WHERE id = 161;
UPDATE directions set iso31661code="586" WHERE id = 162;
UPDATE directions set iso31661code="585" WHERE id = 163;
UPDATE directions set iso31661code="275" WHERE id = 164;
UPDATE directions set iso31661code="591" WHERE id = 165;
UPDATE directions set iso31661code="598" WHERE id = 166;
UPDATE directions set iso31661code="600" WHERE id = 167;
UPDATE directions set iso31661code="604" WHERE id = 168;
UPDATE directions set iso31661code="608" WHERE id = 169;
UPDATE directions set iso31661code="616" WHERE id = 171;
UPDATE directions set iso31661code="620" WHERE id = 172;
UPDATE directions set iso31661code="630" WHERE id = 173;
UPDATE directions set iso31661code="634" WHERE id = 174;
UPDATE directions set iso31661code="638" WHERE id = 175;
UPDATE directions set iso31661code="642" WHERE id = 176;
UPDATE directions set iso31661code="643" WHERE id = 177;
UPDATE directions set iso31661code="646" WHERE id = 178;
UPDATE directions set iso31661code="654" WHERE id = 179;
UPDATE directions set iso31661code="659" WHERE id = 180;
UPDATE directions set iso31661code="662" WHERE id = 181;
UPDATE directions set iso31661code="666" WHERE id = 182;
UPDATE directions set iso31661code="670" WHERE id = 183;
UPDATE directions set iso31661code="882" WHERE id = 184;
UPDATE directions set iso31661code="674" WHERE id = 185;
UPDATE directions set iso31661code="678" WHERE id = 186;
UPDATE directions set iso31661code="682" WHERE id = 187;
UPDATE directions set iso31661code="686" WHERE id = 188;
UPDATE directions set iso31661code="690" WHERE id = 189;
UPDATE directions set iso31661code="694" WHERE id = 190;
UPDATE directions set iso31661code="702" WHERE id = 191;
UPDATE directions set iso31661code="703" WHERE id = 192;
UPDATE directions set iso31661code="705" WHERE id = 193;
UPDATE directions set iso31661code="090" WHERE id = 194;
UPDATE directions set iso31661code="706" WHERE id = 195;
UPDATE directions set iso31661code="710" WHERE id = 196;
UPDATE directions set iso31661code="724" WHERE id = 198;
UPDATE directions set iso31661code="144" WHERE id = 199;
UPDATE directions set iso31661code="729" WHERE id = 200;
UPDATE directions set iso31661code="740" WHERE id = 201;
UPDATE directions set iso31661code="748" WHERE id = 203;
UPDATE directions set iso31661code="752" WHERE id = 204;
UPDATE directions set iso31661code="756" WHERE id = 205;
UPDATE directions set iso31661code="760" WHERE id = 206;
UPDATE directions set iso31661code="158" WHERE id = 207;
UPDATE directions set iso31661code="762" WHERE id = 208;
UPDATE directions set iso31661code="834" WHERE id = 209;
UPDATE directions set iso31661code="764" WHERE id = 210;
UPDATE directions set iso31661code="768" WHERE id = 212;
UPDATE directions set iso31661code="772" WHERE id = 213;
UPDATE directions set iso31661code="776" WHERE id = 214;
UPDATE directions set iso31661code="780" WHERE id = 215;
UPDATE directions set iso31661code="788" WHERE id = 216;
UPDATE directions set iso31661code="792" WHERE id = 217;
UPDATE directions set iso31661code="795" WHERE id = 218;
UPDATE directions set iso31661code="796" WHERE id = 219;
UPDATE directions set iso31661code="798" WHERE id = 220;
UPDATE directions set iso31661code="800" WHERE id = 221;
UPDATE directions set iso31661code="804" WHERE id = 222;
UPDATE directions set iso31661code="784" WHERE id = 223;
UPDATE directions set iso31661code="826" WHERE id = 224;
UPDATE directions set iso31661code="840" WHERE id = 225;
UPDATE directions set iso31661code="858" WHERE id = 227;
UPDATE directions set iso31661code="860" WHERE id = 228;
UPDATE directions set iso31661code="548" WHERE id = 229;
UPDATE directions set iso31661code="862" WHERE id = 230;
UPDATE directions set iso31661code="704" WHERE id = 231;
UPDATE directions set iso31661code="092" WHERE id = 232;
UPDATE directions set iso31661code="850" WHERE id = 233;
UPDATE directions set iso31661code="876" WHERE id = 234;
UPDATE directions set iso31661code="887" WHERE id = 236;
UPDATE directions set iso31661code="894" WHERE id = 238;
UPDATE directions set iso31661code="716" WHERE id = 239;
UPDATE directions set iso31661code="654" WHERE id = 240;
UPDATE directions set iso31661code="000" WHERE id = 241;
UPDATE directions set iso31661code="000" WHERE id = 242;
UPDATE directions set iso31661code="626" WHERE id = 243;
UPDATE directions set iso31661code="000" WHERE id = 246;
UPDATE directions set iso31661code="891" WHERE id = 247;
UPDATE directions set iso31661code="000" WHERE id = 250;
UPDATE directions set iso31661code="000" WHERE id = 251;
UPDATE directions set iso31661code="000" WHERE id = 252;
UPDATE directions set iso31661code="499" WHERE id = 253;
UPDATE directions set iso31661code="000" WHERE id = 254;
UPDATE directions set iso31661code="728" WHERE id = 255;
INSERT INTO currencies (name, full_name, active, exchange_rate, curr_update, curr_edit) SELECT 'AMD', 'Armenian Dram', 0,1,0,1 FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'AMD') = 0;
INSERT IGNORE INTO hangupcausecodes (code, description) SELECT '242','<b>242 - No Rates for Reseller</b><br/>This cause indicates, that reseller does not have rates for the call destination.<br/><br/>What you can do:<br/><ol><li>Check which tariff plan Reseller is using.</li><li>Apply the correct rates for your destination.</li><li>Use Call Tracing to find the exact problem.</li></ol>' FROM dual WHERE NOT EXISTS (SELECT * FROM hangupcausecodes WHERE code = '242');
INSERT IGNORE INTO hangupcausecodes (code, description) SELECT '243','<b>243 - Provider skipped because of CPS limitation</b>' FROM dual WHERE NOT EXISTS (SELECT * FROM hangupcausecodes WHERE code = '243');
INSERT IGNORE INTO hangupcausecodes (code, description) SELECT '244','<b>244 - Device call aborted because of CPS limitation</b>' FROM dual WHERE NOT EXISTS (SELECT * FROM hangupcausecodes WHERE code = '244');
INSERT IGNORE INTO hangupcausecodes (code, description) SELECT '245','<b>245 - Provider skipped because of balance limitation</b>' FROM dual WHERE NOT EXISTS (SELECT * FROM hangupcausecodes WHERE code = '245');
INSERT IGNORE INTO hangupcausecodes (code, description) SELECT '246','<b>246 - Duplicate call hangup</b><br/>This cause prevents you from duplicate calls. It means that two or more calls are sent from the same User account with the same Caller ID and Destination Number.' FROM dual WHERE NOT EXISTS (SELECT * FROM hangupcausecodes WHERE code = '246');
INSERT IGNORE INTO directions (name, code) SELECT 'Thuraya','THU' FROM dual WHERE NOT EXISTS (SELECT * FROM directions WHERE code='THU');
INSERT INTO conflines (name, value, owner_id) SELECT 'load_ok', 1, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'load_ok' and owner_id = 0);
UPDATE users SET lcr_id = 0, tariff_id = 0 WHERE id = 0;
UPDATE conflines SET value = 1 where name = 'Prepaid_Invoice_Address_Format' AND value is NULL;
UPDATE conflines SET value = 'Kolmisoft' WHERE name = 'Company' and value = 'KolmiSoft';
INSERT INTO conflines (name, value, owner_id) SELECT 'GUI_HDD_utilisation', 80, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'GUI_HDD_utilisation' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'GUI_CPU_General_load', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'GUI_CPU_General_load' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'GUI_CPU_Loadstats', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'GUI_CPU_Loadstats' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'GUI_CPU_Ruby_process', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'GUI_CPU_Ruby_process' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'GUI_CPU_asterisk_process', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'GUI_CPU_asterisk_process' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'DB_HDD_utilisation', 80, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'DB_HDD_utilisation' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'DB_CPU_General_load', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'DB_CPU_General_load' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'DB_CPU_Loadstats', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'DB_CPU_Loadstats' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'DB_CPU_MySQL_process', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'DB_CPU_MySQL_process' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'DB_CPU_asterisk_process', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'DB_CPU_asterisk_process' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Delete_Server_Load_stats_older_than', 30, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Delete_Server_Load_stats_older_than' and owner_id = 0);
INSERT IGNORE INTO acc_rights (name,nice_name,permission_group,right_type) VALUES ('pbx_functions', 'Pbx_functions', 'Plugins', 'reseller');
INSERT INTO conflines (name, value, owner_id) SELECT 'Kill_Call_if_PDD_more_than', '0.0', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Kill_Call_if_PDD_more_than' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Kill_Call_if_PDD_less_than', '0.0', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Kill_Call_if_PDD_less_than' and owner_id = 0);
UPDATE devices SET timerb=NULL WHERE timerb=6400;
UPDATE `conflines` SET value = 'Outstanding balance(Debt)' WHERE value = 'Your balance';
INSERT IGNORE INTO hangupcausecodes (code, description) SELECT '248','<b>248 - Call was terminated because FAS (False Answer Supervision) control detected an issue.</b><br/><br/>Possible issues:<br/><br/>1. Bad quality of Provider<br/>2. Provider uses FAS' FROM dual WHERE NOT EXISTS (SELECT * FROM hangupcausecodes WHERE code = '248');
INSERT INTO conflines (name, value, owner_id) SELECT 'AD_sounds_path', '/var/lib/asterisk/sounds/mor/ad', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'AD_sounds_path' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Show_Usernames_On_Pdf_Csv_Export_Files_In_Last_Calls', 0, 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Show_Usernames_On_Pdf_Csv_Export_Files_In_Last_Calls' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Invoice_Bank_Details_Line6', '', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Invoice_Bank_Details_line6' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Invoice_Bank_Details_Line7', '', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Invoice_Bank_Details_line7' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Invoice_Bank_Details_Line8', '', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Invoice_Bank_Details_line8' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Prepaid_Invoice_Bank_Details_Line6', '', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Prepaid_Invoice_Bank_Details_Line6' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Prepaid_Invoice_Bank_Details_Line7', '', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Prepaid_Invoice_Bank_Details_Line7' and owner_id = 0);
INSERT INTO conflines (name, value, owner_id) SELECT 'Prepaid_Invoice_Bank_Details_Line8', '', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Prepaid_Invoice_Bank_Details_Line8' and owner_id = 0);
INSERT IGNORE INTO hangupcausecodes (code, description) SELECT '247','<b>247 - Dead Provider skipped</b><br/>Provider used to terminate the call was disabled by MOR because it was unreachable.<br/>Functionality which disables provider can be disabled/enabled by option "Periodic check" in Provider settings, SIP Specific section.' FROM dual WHERE NOT EXISTS (SELECT * FROM hangupcausecodes WHERE code = '247');
UPDATE currencies SET name = 'ZMW' WHERE name = 'ZMK';
UPDATE devices SET ipaddr='0.0.0.0', name=CONCAT('ipauth', SUBSTR(md5(RAND()), 1, 10)) WHERE user_id IN (SELECT id FROM users WHERE usertype = 'reseller' OR usertype='admin') AND name NOT LIKE 'ipauth%' AND name NOT LIKE 'mor_server%';
UPDATE conflines SET value = 'International Date Line West' WHERE value = -11 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Hawaii' WHERE value = -10 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Alaska' WHERE value = -9 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Pacific Time (US & Canada)' WHERE value = -8 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Arizona' WHERE value = -7 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Central America' WHERE value = -6 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Bogota' WHERE value = -5 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Caracas' WHERE value = -4.5 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Atlantic Time (Canada)' WHERE value = -4 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Newfoundland' WHERE value = -3.5 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Brasilia' WHERE value = -3 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Mid-Atlantic' WHERE value = -2 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Azores' WHERE value = -1 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'London' WHERE value = '0' AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Amsterdam' WHERE value = 1 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Athens' WHERE value = 2 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Baghdad' WHERE value = 3 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Abu Dhabi' WHERE value = 4 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Islamabad' WHERE value = 5 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Chennai' WHERE value = 5.5 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Kathmandu' WHERE value = 5.75 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Almaty' WHERE value = 6 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Rangoon' WHERE value = 6.5 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Bangkok' WHERE value = 7 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Beijing' WHERE value = 8 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Irkutsk' WHERE value = 9 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Adelaide' WHERE value = 9.5 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Brisbane' WHERE value = 10 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'New Caledonia' WHERE value = 11 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = 'Auckland' WHERE value = 12 AND name = 'Default_User_time_zone';
UPDATE conflines SET value = "Nuku'alofa" WHERE value = 13 AND name = 'Default_User_time_zone';
INSERT IGNORE INTO acc_rights (name, nice_name, permission_group, right_type) VALUES ('call_tracing_usage', 'call_tracing_usage', 'Functions', 'accountant');
INSERT IGNORE INTO acc_rights (name, nice_name, permission_group, right_type) VALUES ('provider', 'Provider', 'Active_Calls', 'accountant');
UPDATE conflines SET value = '25' WHERE value = '10' AND name = 'Backup_disk_space';
UPDATE conflines SET value = 140 WHERE name = 'mor_mapped_db_version';
INSERT IGNORE INTO conflines (name, value) SELECT 'mor_mapped_db_version', '140' FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'mor_mapped_db_version');
INSERT IGNORE INTO conflines (name, value) SELECT 'AST_18', '1' FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'AST_18');
update conflines set value = 0 where name = 'google_checkout_google_checkout_enabled';
INSERT IGNORE INTO conflines (name,value) SELECT 'Max_PDF_pages', 100 FROM DUAL WHERE (SELECT COUNT(*) FROM conflines WHERE name = 'Max_PDF_pages') = 0;
UPDATE hangupcausecodes SET description='<b>247 - Dead Provider skipped</b><br/>Provider used to terminate the call was disabled by MOR because it was unreachable.<br/>Functionality which disables provider can be disabled/enabled by option "Periodic check" in Provider settings, SIP Specific section.' WHERE code = '247';
INSERT IGNORE INTO conflines (name, value) SELECT 'Hide_active_calls_longer_than', 4 FROM dual WHERE NOT EXISTS (SELECT * FROM conflines where name = 'Hide_active_calls_longer_than' and owner_id = 0);
DELETE FROM devicecodecs WHERE device_id IN (SELECT id FROM devices WHERE device_type = 'FAX');
INSERT INTO devicecodecs (device_id, codec_id, priority) (SELECT id, 1, 0 FROM devices WHERE device_type = "FAX");
INSERT INTO devicecodecs (device_id, codec_id, priority) (SELECT id, 2, 0 FROM devices WHERE device_type = "FAX");
UPDATE conflines SET value = 80 WHERE value = 50 AND name = 'GUI_HDD_utilisation' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 90 AND name = 'GUI_CPU_General_load' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 4 AND name = 'GUI_CPU_Loadstats' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 90 AND name = 'GUI_CPU_Ruby_process' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 90 AND name = 'GUI_CPU_asterisk_process' and owner_id = 0;
UPDATE conflines SET value = 80 WHERE value = 50 AND name = 'DB_HDD_utilisation' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 90 AND name = 'DB_CPU_General_load' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 4 AND name = 'DB_CPU_Loadstats' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 90 AND name = 'DB_CPU_MySQL_process' and owner_id = 0;
UPDATE conflines SET value = 0 WHERE value = 90 AND name = 'DB_CPU_asterisk_process' and owner_id = 0;
UPDATE hangupcausecodes SET description = '<b>224 - Provider skipped because his rate is higher than users rate.</b><br>System saves system owner from taking loss from such call when self cost is higher when sell price.<br>Call Tracing is best tool to troubleshoot this problem. For more info consult online manual at wiki.kolmisoft.com<br>' WHERE code = 224 AND description = '<b>224 - Provider skipped because his rate is higher then users rate.</b><br>System saves system owner from taking loss from such call when self cost is higher when sell price.<br>Call Tracing is best tool to troubleshoot this problem. For more info consult online manual at wiki.kolmisoft.com<br>';
UPDATE emails SET body = 'Balance: <%= balance %> <%= currency %>' WHERE name = 'warning_balance_email' AND body = 'Balance: <%=balance %>';
DELETE FROM conflines WHERE name = 'Default_device_qualify_time';
# ^^^^^^ WRITE ABOVE THIS LINE ^^^^^
# marking that DB is updated from script
INSERT INTO conflines (name, value) VALUES ('DB_Update_From_Script', 1);
