#!/bin/sh

clear

echo 
echo
echo "	9999999999999h999999999999999999h999hh9999999999999h999999h999h99999999999hh9999999999999999999999999999999h"
echo "	hX333333333333333333333333X3333333333333333333333333333X33333333333333333333333333333333333333333333333333X9"
echo "	h9GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGhG"
echo "	G9GGGG&AAAh&AA&GGGhGG&AAAAAA&&GGGhGGG&AA&GGGGGhGAAAA&GGh&&AAAGGGGAAAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGhG"
echo "	&hG&G&&HBHHAHHAA&GGHBBAh33h&HBHA&GGG&AHBBAGGGG&&HBMBHAGGHABBBA&G&ABHAGGGGGGGGGGGGGGGGGGGGG&&GGGGGGGGGGGGGGGG"
echo "	&GG&&M:  :@,  ;#AAH9s::,...,;5AMB&GAG   5#AGG&H.    A#AA,   .@HAr  .#M&GG&&&&&&&&&&&&&&&&&&&&&&&GGGGGGG&&&G&"
echo "	&G&G&@,  ,@   &@B9.     ..  ..:5B#AAA   2@AGG&@     S@M3     @MB;   @#G&&&&&&&&&&&&&&&&&&&G&AAAAG&&&&G&&&&G&"
echo "	&G&G&@;  ;A  ;@#Ar  .  .,.     .rA#MB   h@A&GA@,    ,@@i     @##i  .@#&GG&&&&A&AG&&&AAA&&&HMBA&AABMMHA&&&&G&"
echo "	&&A&A@r  ,;  #@Hh3Xr:;;:;rr;;,,;rrA@@   9@H&AA@:     M@:     @#@S  .@#A&&AH####BAAM####HAM&.  :M@r ,MMAA&&&A"
echo "	A&AAA@r     :@@A2M@GrSss3M#@@#@H&rs@@   h@H&AH@:  ,  i@  :   @#@5  .@#AAAHhr::;G#B2:,;SBBs   :#A:   2#HAAA&A"
echo "	A&AAA@r  ,: ,@#BShHGirr9H2iShAG39Sr@@   9@H&AH@:  3; .A  &   @@@5  .@#AABS  .  r@,     9@.  r2@2   r3#HAAA&A"
echo "	A&AAH@r  iA  h@#2r;:::;;;,..  ,s5;;@@   h@HAAH@:  hA    ;#   @@@5  .@#ABA  :@  @h  Ms ,@@, ;@@@H  A@@BAAAAAA"
echo "	AAAAH@r  i@  .@@H2r:;::rr:,.    ,,S@@   G@BHAH@:  X@    H#   @@@2  .@@AM@;  ,h@@  s@  #@2  @@#@. :@@BAAAAAAA"
echo "	AAAAH@r  ;@,  9@@M9irrSh&3r:,..r22@@@   &@@#MB@:  S@,   @B   @@@2   @@BX,;A,  @2  @, r@@  r@##S  #@M&AAAAAAA"
echo "	HAAAH@;  ,@2   @@@#5iX3293s;;rG#@@@@#       h@@.  r@i  .@h   @@@S   @@B.  2  9@  ri  @@:  @@#A   h@HAHAAAAAA"
echo "	HAAAB@2..r@@: .H@#@@#A3399ABB#@@@#B#@;.,    B@@s..2@#:.5@H..;@@@G..;@@#s.,:;A@@; ,,s@@M, X@##B;. ;@MHAHHHHAH"
echo "	HAHHB@@@@@@@@@@@#MB@@@##MM@@@@@@#HAM@@@@@@@@@@@@@@@@@@@@@@@@@@M#@@@@@#@@@@@@@@@@@@@@@@@@@@@HM@@@@@@HHHHHHHAH"
echo "	HHHHB@X::i@Br:;A#BBHAh9hGh3X2XGABMM##i;rr;;:H#@5;:2@A;:i@A::r@##G;;r###2;rrr2@#s;srrG@#s,S@M#Ms;;SMMHHHHHHHH"
echo "	HHHHB#GiiX@&iS9#MBA99&AAAAh3229GABMM#2S2GAG9HM#3ish@Gii2#Hii2#M#ASi2###hiXB5rh@2SAAssB@AiiA##MXi2B#BHHHHHHHH"
echo "	BHHHB#HGhA#Ah&M#BHAAAAAHHHAA&hGGGAB#MAGA#@@#BH#AG9H#AGGhB#hG&MMMBhh&#MM#MHMA3G##GG#HX&##AXGMM##&hMMBBBHBBBHB"
echo "	BHBBB#MHHB#HHB#MHHHBBHHBBHBBHHHHAAHM#MHB##MMBB#MBHB#HHBAM#HHHMMM#HHHMMM##MAHBM#@MAM#HAM#MAAHM##MAABMBBBBBBHB"
echo "	BBBBMMMBBBBBBMMBBBBBBBBBMMMBBMBMMBBMMMBHMMBBMMMBBBMMBMMBMMBBBMMMMBMHMMMMMMBM#HAM#BB#MHB#MMHHMMM#BHBMBBMMMBBB"
echo "	MBMMMMMBMMMMMMBMMMMMMMMMMMMMMMMMMBBMMMMBBMBBBMMMBBMMMMMMMMMMBMMMMBMBMBBMMMMMMBBMMMMMMBBMMMBBBMM#MBBBBMMMMBBM"
echo "	MBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBM"
echo "	MBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBM"
echo 
echo
