
#################### MOR PRO 0.7 ############################


# --------------- DELETE HANGUPCAUSE CODES -----------------

DELETE FROM hangupcausecodes;


# --------------- INSERT HANGUPCAUSE CODES -----------------

INSERT INTO hangupcausecodes (code, description) VALUES ('0', '<b>0 - Unknow error</b><br>This is usually given by the router when none of the other codes apply. This cause usually occurs in the same type of situations as cause 1, cause 88, and cause 100.<br>'); 
INSERT INTO hangupcausecodes (code, description) VALUES ('1', '<b>1 - Unallocated (unassigned) number.</b><br>This cause indicates that the destination requested by the calling user cannot be reached because, although the number is in a valid format, it is not currently assigned (allocated).<br><br>What it usually means:<br><ol><li>The SPIDS may be incorrectly entered in the router or the Telco switch, giving a SPID failure in the router logs.</li><li>The ISDN phone number being dialed by the router is invalid and the telco switch cannot locate the number to complete the call, as it is invalid.</li><li>On long distance calls, the call cannot be properly routed to its destination.</li></ol>');
INSERT INTO hangupcausecodes (code, description) VALUES ('2', '<b>2 - No route to specified transit network (national use).</b><br>This cause indicates that the equipment sending this cause has received a request to route the call through a particular transit network which it does not recognize. The equipment sending this cause does not recognize the transit network either because the transit network does not exist or because that particular transit network not serve the equipment which is sending this cause.<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('3', '<b>3 - No route to destination.</b><br>This cause indicates that the called party cannot be reached because the network through which the call has been routed does not serve the destination desired. This cause is supported on a network dependent basis.<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('4', '<b>4 - send special information tone.</b><br>This cause indicates that the called party cannot be reached for reasons that are of a long term nature and that the special information tone should be returned to the calling party.<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('5', '<b>5 - misdialed trunk prefix (national use).</b><br>This cause indicates the erroneous inclusion of a trunk prefix in the called party number. This number is to sniped from the dialed number being sent to the network by the customer premises equipment.<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('6', '<b>6 - channel unacceptable.</b><br>This cause indicates that the channel most recently identified is not acceptable to the sending entity for use in this call.<br>');  
INSERT INTO hangupcausecodes (code, description) VALUES ('7', '<b>7 - call awarded. being delivered in an established channel.</b><br>This cause indicates that the user has been awarded the incoming call and that the incoming call is being connected to a channel already established to that user for similar calls (e.g. packet-mode x.25 virtual calls).<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('8', '<b>8 - preemption.</b><br>This cause indicates the call is being preempted.<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('9', '<b>9 - preemption - circuit reserved for reuse.</b><br>This cause indicates that the call is being preempted and the circuit is reserved for reuse by the preempting exchange.<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('10', '<b>10 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('11', '<b>11 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('12', '<b>12 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('13', '<b>13 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('14', '<b>14 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('15', '<b>15 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('16', '<b>16 - normal call clearing.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('17', '<b>17 - user busy.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('18', '<b>18 - no user responding.');
INSERT INTO hangupcausecodes (code, description) VALUES ('19', '<b>19 - no answer from user (user alerted).</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('20', '<b>20 - subscriber absent.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('21', '<b>21 - call rejected.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('22', '<b>22 - number changed.');
INSERT INTO hangupcausecodes (code, description) VALUES ('23', '<b>23 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('24', '<b>24 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('25', '<b>25 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('26', '<b>26 - non-selected user clearing.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('27', '<b>27 - destination out of order.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('28', '<b>28 - invalid number format (address incomplete).</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('29', '<b>29 - facilities rejected.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('30', '<b>30 - response to STATUS INQUIRY.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('31', '<b>31 - normal. unspecified.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('32', '<b>32 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('33', '<b>33 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('34', '<b>34 - no circuit/channel available.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('35', '<b>35 - Call Queued.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('36', '<b>36 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('37', '<b>37 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('38', '<b>38 - network out of order.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('39', '<b>39 - permanent frame mode connection out-of-service.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('40', '<b>40 - permanent frame mode connection operational.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('41', '<b>41 - temporary failure.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('42', '<b>42 - switching equipment congestion.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('43', '<b>43 - access information discarded.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('44', '<b>44 - requested circuit/channel not available.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('45', '<b>45 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('46', '<b>46 - precedence call blocked.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('47', '<b>47 - resource unavailable, unspecified.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('48', '<b>48 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('49', '<b>49 - Quality of Service not available.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('50', '<b>50 - requested facility not subscribed.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('51', '<b>51 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('52', '<b>52 - outgoing calls barred</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('53', '<b>53 - outgoing calls barred within CUG.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('54', '<b>54 - incoming calls barred</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('55', '<b>55 - incoming calls barred within CUG.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('56', '<b>56 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('57', '<b>57 - bearer capability not authorized.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('58', '<b>58 - bearer capability not presently available.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('59', '<b>59 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('60', '<b>60 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('61', '<b>61 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('62', '<b>62 - inconsistency in outgoing information element.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('63', '<b>63 - service or option not available. unspecified.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('64', '<b>64 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('65', '<b>65 - bearer capability not implemented.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('66', '<b>66 - channel type not implemented.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('67', '<b>67 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('68', '<b>68 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('69', '<b>69 - requested facility not implemented.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('70', '<b>70 - only restricted digital information bearer capability is available.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('71', '<b>71 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('72', '<b>72 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('73', '<b>73 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('74', '<b>74 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('75', '<b>75 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('76', '<b>76 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('77', '<b>77 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('78', '<b>78 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('79', '<b>79 - service or option not implemented unspecified.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('80', '<b>80 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('81', '<b>81 - invalid call reference value.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('82', '<b>82 - identified channel does not exist.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('83', '<b>83 - a suspended call exists, but this call identify does not.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('84', '<b>84 - call identity in use.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('85', '<b>85 - no call suspended.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('86', '<b>86 - call having the requested call identity has been cleared.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('87', '<b>87 - user not a member of CUG.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('88', '<b>88 - incompatible destination.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('89', '<b>89 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('90', '<b>90 - non-existent CUG.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('91', '<b>91 - invalid transit network selection (national use).</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('92', '<b>92 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('93', '<b>93 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('94', '<b>94 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('95', '<b>95 - invalid message, unspecified.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('96', '<b>96 - mandatory information element is missing.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('97', '<b>97 - message type non-existent or not implemented.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('98', '<b>98 - message not compatible with call state or message type non-existent.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('99', '<b>99 - Information element / parameter non-existent or not implemented.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('100', '<b>100 - Invalid information element contents.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('101', '<b>101 - message not compatible with call state.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('102', '<b>102 - recovery on timer expiry.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('103', '<b>103 - parameter non-existent or not implemented - passed on (national use).</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('104', '<b>104 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('105', '<b>105 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('106', '<b>106 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('107', '<b>107 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('108', '<b>108 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('109', '<b>109 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('110', '<b>110 - message with unrecognized parameter discarded.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('111', '<b>111 - protocol error, unspecified.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('112', '<b>112 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('113', '<b>113 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('114', '<b>114 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('115', '<b>115 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('116', '<b>116 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('117', '<b>117 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('118', '<b>118 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('119', '<b>119 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('120', '<b>120 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('121', '<b>121 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('122', '<b>122 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('123', '<b>123 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('124', '<b>124 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('125', '<b>125 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('126', '<b>126 - Not standart error code. Consult with Provider.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('127', '<b>127 - Intel-working, unspecified.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('200', '<b>200 - MOR can\'t determine who is calling</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('201', '<b>201 - User is blocked</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('202', '<b>202 - Reseller is blocked</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('203', '<b>203 - No rates for user</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('204', '<b>204 - No suitable providers found</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('205', '<b>205 - MOR PRO not authorized to work on this computer</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('206', '<b>206 - server_id is not set in mor.conf file</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('207', '<b>207 - Not clear who should receive call</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('208', '<b>208 - MOR can not make more calls</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('210', '<b>210 - Balance > 0, but not enough to make call 1s in length</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('211', '<b>211 - Low balance for user</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('212', '<b>212 - Too low balance for more simultaneous calls</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('213', '<b>213 - Low balance for DID owner</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('214', '<b>214 - Too low balance for DID owner for more simultaneous calls</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('215', '<b>215 - Low balance for reseller</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('216', '<b>216 - Too low balance for reseller for more simultaneous calls</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('217', '<b>217 - Callback not initiated because device not found by ANI</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('218', '<b>218 - Reseller does now allow loss calls</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('219', '<b>219 - DID has reached call limit.</b><br>No more calls allowed to this DID.<br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('220', '<b>220 - User call limit reached.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('221', '<b>221 - Device call limit reached.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('222', '<b>222 - Resellers call limit reached.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('223', '<b>223 - Provider skipped because his rate is higher then users rate.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('224', '<b>224 - Providers call limit reached.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('225', '<b>225 - CallerID is banned</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('226', '<b>226 - DID is free</b><br>');

INSERT INTO hangupcausecodes (code, description) VALUES ('230', '<b>230 -  Connection returned error code 0 instead of real code.</b><br>');
INSERT INTO hangupcausecodes (code, description) VALUES ('231', '<b>231 -  Provider unreachable. </b><br>');

