

#################### MOR PRO 0.7 ############################


# --------------- INSERT CURRENCIES -----------------

INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Albanian Lek', 'ALL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ALL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Algerian Dinar', 'DZD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'DZD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Argentinian Peso', 'ARS', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ARS') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Aruban Florin', 'AWG', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'AWG') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Australian Dollar', 'AUD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'AUD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Austrian Schilling', 'ATS', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ATS') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Bahraini Dinar', 'BHD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BHD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Bangladesh Taka', 'BDT', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BDT') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Barbados Dollar', 'BBD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BBD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Belgian Franc', 'BEF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BEF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Belize Dollar', 'BZD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BZD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Bermuda Dollar', 'BMD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BMD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Bhutan Ngultrum', 'BTN', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BTN') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Bolivian Boliviano', 'BOB', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BOB') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Botswana Pula', 'BWP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BWP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Brazilian Real', 'BRL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BRL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'British Pound', 'GBP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GBP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Brunei Dollar', 'BND', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BND') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Bulgarian Lev', 'BGN', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BGN') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Cambodian Riel', 'KHR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'KHR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Canadian Dollar', 'CAD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CAD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Cape Verde Escudo', 'CVE', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CVE') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Cayman Islands Dollar', 'KYD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'KYD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'CFA Franc', 'BCEAO', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BCEAO') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'CFA Franc', 'XOF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'XOF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'CFA Franc', 'XAF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'XAF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'CFA Franc', 'BEAC', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'BEAC') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'CFP Franc', 'XPF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'XPF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Chilean Peso', 'CLP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CLP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Colombian Peso', 'COP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'COP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Comoros Franc', 'KMF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'KMF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Costa Rican Colon', 'CRC', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CRC') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Croatian Kuna', 'HRK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'HRK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Cuban Peso', 'CUP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CUP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Cypriot Pound', 'CYP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CYP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Czech Koruna', 'CZK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CZK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Danish Krone', 'DKK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'DKK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Djibouti Franc', 'DJF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'DJF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Dominican Peso', 'DOP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'DOP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Dutch Guilder', 'NLG', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'NLG') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'East Caribbean Dollar', 'XCD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'XCD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Egyptian Pound', 'EGP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'EGP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'El Salvador Colon', 'SVC', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SVC') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Estonian Kroon', 'EEK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'EEK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Ethiopian Birr', 'ETB', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ETB') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Euro', 'EUR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'EUR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Fiji Dollar', 'FJD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'FJD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Finnish Markka', 'FIM', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'FIM') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'French Franc', 'FRF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'FRF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Gambia Dalasi', 'GMD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GMD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'German Mark', 'DEM', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'DEM') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Ghanaian Cedi', 'GHC', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GHC') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Gibraltar Pound', 'GIP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GIP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Greek Drachma', 'GRD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GRD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Guatemala Quetzal', 'GTQ', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GTQ') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Guinea Franc', 'GNF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GNF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Guyana Dollar', 'GYD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'GYD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Haitian Gourde', 'HTG', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'HTG') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Honduras Lempira', 'HNL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'HNL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Hong Kong Dollar', 'HKD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'HKD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Hungarian Forint', 'HUF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'HUF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Iceland Krona', 'ISK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ISK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Indian Rupee', 'INR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'INR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Indonesian Rupiah', 'IDR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'IDR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Irish Punt', 'IEP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'IEP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Israeli Shekel', 'ILS', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ILS') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Italian Lira', 'ITL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ITL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Jamaican Dollar', 'JMD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'JMD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Japanese Yen', 'JPY', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'JPY') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Jordanian Dinar', 'JOD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'JOD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Kenyan Shilling', 'KES', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'KES') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Kuwaiti Dinar', 'KWD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'KWD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Laos Kip', 'LAK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'LAK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Latvian Lats', 'LVL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'LVL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Lebanese Pound', 'LBP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'LBP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Lesotho Loti', 'LSL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'LSL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Lithuanian Litas', 'LTL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'LTL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Malagasy Franc', 'MGF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MGF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Malawi Kwacha', 'MWK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MWK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Malaysian Ringgit', 'MYR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MYR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Maldives Rufiyan', 'MVR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MVR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Maltese Pound', 'MTL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MTL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Mauritania Ouguiya', 'MRO', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MRO') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Mauritius Rupee', 'MUR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MUR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Mexican Peso', 'MXN', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MXN') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Mongolian Tugrik', 'MNT', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MNT') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Moroccan Dirham', 'MAD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MAD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Mozambique Metical', 'MZM', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MZM') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Myanmar Kyat', 'MMK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'MMK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Namibian Dollar', 'NAD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'NAD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Nepal Rupee', 'NPR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'NPR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Netherlands Antilles Guilder', 'ANG', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ANG') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'New Zealand Dollar', 'NZD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'NZD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Nicaraguan Cordoba', 'NIO', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'NIO') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Nigerian Naira', 'NGN', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'NGN') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Norwegian Krone', 'NOK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'NOK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Oman Rial', 'OMR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'OMR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Pakistani Rupee', 'PKR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'PKR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Papua New Guinea Kina', 'PGK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'PGK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Peruvian Sol', 'PEN', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'PEN') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Philippines Peso', 'PHP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'PHP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Polish Zloty', 'PLN', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'PLN') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Portuguese Escudo', 'PTE', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'PTE') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Qatari Rial', 'QAR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'QAR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Renmimbi Yuan', 'CNY', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CNY') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Romanian Leu', 'ROL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ROL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Russian Ruble', 'RUB', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'RUB') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Salomon Islands Dollar', 'SBD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SBD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Sao Tome & Principe Dobra', 'STD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'STD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Saudi Arabian Riyal', 'SAR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SAR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Seychelles Rupee', 'SCR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SCR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Sierra Leone Leone', 'SLL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SLL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Singapore Dollar', 'SGD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SGD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Slovak Koruna', 'SKK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SKK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Slovenian Tolar', 'SIT', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SIT') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'South African Rand', 'ZAR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ZAR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'South Korean Won', 'KRW', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'KRW') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Spanish Peseta', 'ESP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ESP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Sri Lanka Rupee', 'LKR', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'LKR') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'St. Helena Pound', 'SHP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SHP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Sudanese Dinar', 'SDD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SDD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Surinam Guilder', 'SRG', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SRG') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Swaziland Lilangeni', 'SZL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SZL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Swedish Krona', 'SEK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SEK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Swiss Franc', 'CHF', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'CHF') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Syria Pound', 'SYP', '0', '1'  FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'SYP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Taiwan New Dollar', 'TWD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'TWD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Tanzanian Shilling', 'TZS', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'TZS') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Thai Baht', 'THB', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'THB') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Tonga Isl Paanga', 'TOP', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'TOP') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Trinidad Dollar', 'TTD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'TTD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Tunisian Dinar', 'TND', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'TND') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Turkish Lira', 'TRL', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'TRL') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Ugandan Shilling', 'UGX', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'UGX') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Ukraine Hryvnia', 'UAH', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'UAH') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'United Arab Emirates Dirham', 'AED', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'AED') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'US Dollar', 'USD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'USD') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Vanuatu Vatu', 'VUV', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'VUV') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Venezuelan Bolivar', 'VEB', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'VEB') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Vietnam Dong', 'VND', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'VND') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Western Samoa Tala', 'WST', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'WST') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Zambia Kwacha', 'ZMK', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ZMK') = 0;
INSERT INTO currencies (full_name, name, active, exchange_rate) SELECT 'Zimbabwean Dollar', 'ZWD', '0', '1' FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'ZWD') = 0;
