ALTER TABLE payments CHANGE hash payment_hash varchar(32);
ALTER TABLE monitorings MODIFY monitoring_type enum('bellow', 'above', 'simultaneous') NOT NULL DEFAULT 'above';
ALTER TABLE devices ADD COLUMN qf_tell_balance TINYINT NOT NULL DEFAULT 0;
ALTER TABLE devices ADD COLUMN qf_tell_time TINYINT NOT NULL DEFAULT 0;
ALTER TABLE lcrs ADD COLUMN no_failover TINYINT NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS `call_details` (`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `call_id` bigint(20) DEFAULT NULL, `pdd` double DEFAULT NULL, `la_ip` int(11) DEFAULT NULL, `la_local_ip` int(11) DEFAULT NULL, `la_codec` int(11) DEFAULT NULL, `la_rtt` double DEFAULT NULL, `la_r` int(11) DEFAULT NULL, `la_mos` double DEFAULT NULL, `la_rxcount` int(11) DEFAULT NULL, `la_lp` int(11) DEFAULT NULL, `la_rxjitter` double DEFAULT NULL, `la_r_r` int(11) DEFAULT NULL, `la_r_mos` double DEFAULT NULL, `la_tx_count` int(11) DEFAULT NULL, `la_rlp` int(11) DEFAULT NULL, `la_txjitter` double DEFAULT NULL, `la_t_r` int(11) DEFAULT NULL, `la_t_mos` double DEFAULT NULL, `lb_ip` int(11) DEFAULT NULL, `lb_local_ip` int(11) DEFAULT NULL, `lb_codec` tinyint(4) DEFAULT NULL, `lb_rtt` double DEFAULT NULL, `lb_r` int(11) DEFAULT NULL, `lb_mos` double DEFAULT NULL, `lb_rxcount` int(11) DEFAULT NULL, `lb_lp` int(11) DEFAULT NULL, `lb_rxjitter` double DEFAULT NULL, `lb_r_r` int(11) DEFAULT NULL, `lb_r_mos` double DEFAULT NULL, `lb_txcount` int(11) DEFAULT NULL, `lb_rlp` int(11) DEFAULT NULL, `lb_txjitter` double DEFAULT NULL, `lb_t_r` int(11) DEFAULT NULL, `lb_t_mos` double DEFAULT NULL, `peerip` int(10) unsigned DEFAULT NULL, `recvip` int(10) unsigned DEFAULT NULL, `sipfrom` varchar(255) DEFAULT NULL, `uri` varchar(255) DEFAULT NULL, `useragent` varchar(255) DEFAULT NULL, `peername` varchar(255) DEFAULT NULL, `t38passthrough` tinyint(4) DEFAULT NULL, INDEX call_id_index (call_id), PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE devices ADD COLUMN anti_resale_auto_answer TINYINT DEFAULT 0 NOT NULL;
ALTER TABLE providers ADD COLUMN balance DOUBLE DEFAULT 0 NOT NULL;
ALTER TABLE devices ADD COLUMN time_limit_per_day INT NOT NULL DEFAULT 0;
ALTER TABLE `lcrproviders` ADD INDEX `active_lcr_prov` ( `active` , `lcr_id` , `provider_id` );
ALTER TABLE `activecalls` ADD INDEX `prov_index` ( `provider_id` );
ALTER TABLE devices ADD COLUMN control_callerid_by_cids TINYINT NOT NULL DEFAULT 0;
ALTER TABLE `callerids` ADD INDEX `cli_device_id` ( `cli` , `device_id` );
ALTER TABLE dids ADD COLUMN tonezone VARCHAR(5) DEFAULT NULL;
#alter table acc_groups change description description text;
#alter table cron_settings change description description text;
#alter table hangupcausecodes change description description text;
#alter table payments change description description text;
#alter table ringgroups change comment comment text;
#alter table invoices change comment comment text;
#alter table cs_invoices change comment comment text;
#alter table callerids change comment comment text;
#alter table call_logs change log log text;
#alter table conflines change value2 value2 text;
#alter table cron_actions change last_error last_error text;
#alter table emails change body body text;
ALTER TABLE devices ADD COLUMN callerid_advanced_control TINYINT NOT NULL DEFAULT 0;
ALTER TABLE cards MODIFY COLUMN number VARCHAR(255) DEFAULT NULL;
ALTER TABLE cards MODIFY COLUMN pin VARCHAR(255) DEFAULT NULL;
ALTER TABLE cards ADD COLUMN hidden TINYINT NOT NULL DEFAULT 0;
INSERT IGNORE INTO currencies (name, full_name, active) SELECT 'GEL', 'Georgian lari', 0 FROM dual WHERE NOT EXISTS (SELECT * FROM currencies WHERE name = 'GEL');
ALTER TABLE lcrs MODIFY COLUMN no_failover tinyint NOT NULL DEFAULT 0;
UPDATE lcrs LEFT JOIN providers ON (lcrs.failover_provider_id = providers.id) SET lcrs.failover_provider_id = NULL WHERE providers.id IS NULL;
ALTER TABLE lcrs MODIFY COLUMN failover_provider_id BIGINT DEFAULT NULL;
ALTER TABLE lcrs ADD INDEX failover_provider_index (failover_provider_id);
ALTER TABLE lcrs DROP FOREIGN KEY `failover_provider`;
ALTER TABLE `lcrs` ADD CONSTRAINT `failover_provider` FOREIGN KEY(`failover_provider_id`) REFERENCES `providers`(`id`);
ALTER TABLE cards ADD call_count INT default 0;
ALTER TABLE dids ADD call_count INT default 0;
ALTER TABLE cardgroups ADD COLUMN hidden TINYINT NOT NULL DEFAULT 0;
DELETE lcrproviders FROM lcrproviders LEFT JOIN lcrs ON(lcrs.id = lcrproviders.lcr_id) WHERE lcrs.id IS NULL;
ALTER TABLE lcrproviders DROP FOREIGN KEY `lcrproviders_ibfk`;
ALTER TABLE lcrproviders ADD CONSTRAINT lcrproviders_ibfk FOREIGN KEY (lcr_id) REFERENCES lcrs(id);
ALTER TABLE extlines MODIFY COLUMN appdata varchar(255);
ALTER TABLE groups AUTO_INCREMENT = 1;
ALTER TABLE flatrate_data ADD COLUMN seconds INT NOT NULL DEFAULT 0;
ALTER TABLE devices ADD COLUMN transport enum('udp','tcp','udp,tcp','tcp,udp') DEFAULT 'udp';
ALTER TABLE servers ADD COLUMN version VARCHAR(30) DEFAULT NULL;
ALTER TABLE servers ADD COLUMN uptime VARCHAR(50) DEFAULT NULL;
CREATE TABLE IF NOT EXISTS `devicerules` (  `id` int(11) NOT NULL auto_increment, `device_id` int(11) NOT NULL, `name` varchar(255) default NULL, `enabled` tinyint(4) NOT NULL default '1', `cut` varchar(255) default NULL, `add` varchar(255) default NULL,  `minlen` int(11) NOT NULL default '1', `maxlen` int(11) NOT NULL default '100', `pr_type` enum('dst','src') default 'dst', PRIMARY KEY  (`id`) ) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
ALTER TABLE devices MODIFY COLUMN control_callerid_by_cids int(11) DEFAULT NULL;
alter table devices add column subscribemwi enum('yes','no') DEFAULT NULL;
update devices set subscribemwi = ABS(enable_mwi -1) + 1;
ALTER TABLE payments ADD provider_id INT default -1 COMMENT 'Provider ID';
ALTER TABLE cards ADD min_balance float default 0 COMMENT 'Card minimal balance';
ALTER TABLE dids ADD COLUMN cc_tariff_id INT UNSIGNED DEFAULT 0;
ALTER TABLE `codecs` ADD UNIQUE (`name`);
ALTER TABLE `adnumbers` ADD `uniqueid` VARCHAR( 30 ) NULL ;
ALTER TABLE `servers` CHANGE `uptime` `uptime` VARCHAR( 150 );
ALTER TABLE devices ADD COLUMN encryption enum('yes','no') DEFAULT 'no';
alter table devices add column block_callerid int default 0;
CREATE TABLE IF NOT EXISTS ivr_action_logs (id INT NOT NULL AUTO_INCREMENT ,created_at DATETIME NULL ,action_text VARCHAR( 255 ) NULL ,uniqueid VARCHAR( 30 ) NULL ,adnumber_id INT NULL ,PRIMARY KEY ( id )) ENGINE = InnoDB ;
ALTER TABLE ivr_action_logs ADD INDEX ( adnumber_id ) ;
#CREATE INDEX uniqueidindex ON calls (uniqueid(6)); #helps a lot for recording/adnumber selection issues, but takes a lot of time to create such index
ALTER TABLE users ADD webphone_allow_use  INT default 0 COMMENT 'webphone enabled for user';
ALTER TABLE users ADD webphone_device_id INT default 0 COMMENT 'webphone device id';
CREATE TRIGGER validate_device_update BEFORE UPDATE ON devices FOR EACH ROW SET NEW.callgroup = IF(NEW.callgroup < 0 OR NEW.callgroup > 63, OLD.callgroup, NEW.callgroup);
CREATE TRIGGER validate_device_insert BEFORE INSERT ON devices FOR EACH ROW SET NEW.callgroup = IF(NEW.callgroup < 0 OR NEW.callgroup > 63, NULL, NEW.callgroup);
ALTER TABLE recordings ADD INDEX ( visible_to_user ) ;
ALTER TABLE recordings ADD INDEX ( src_device_id ) ;
CREATE INDEX uniqueidindex ON recordings (uniqueid(6));
ALTER TABLE services MODIFY COLUMN servicetype ENUM('flat_rate', 'one_time_fee', 'periodic_fee');
ALTER TABLE services MODIFY COLUMN periodtype ENUM('day', 'month');
ALTER TABLE cardgroups ADD COLUMN callerid_leave TINYINT NOT NULL DEFAULT 0;
DROP TABLE IF EXISTS c2c_calls;
DROP TABLE IF EXISTS c2c_campaigns;
DROP TABLE IF EXISTS c2c_comments;
DROP TABLE IF EXISTS c2c_commfields;
DROP TABLE IF EXISTS c2c_invoicedetails;
DROP TABLE IF EXISTS c2c_invoices;
ALTER TABLE activecalls MODIFY user_rate DECIMAL(30,15) DEFAULT 0;
ALTER TABLE activecalls MODIFY pdd DECIMAL(30,15) DEFAULT 0;
ALTER TABLE acustratedetails MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE aratedetails MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY pdd DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY la_rtt DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY la_mos DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY la_rxjitter DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY la_r_mos DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY la_txjitter DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY la_t_mos DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY lb_rtt DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY lb_mos DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY lb_rxjitter DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY lb_r_mos DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY lb_txjitter DECIMAL(30,15) DEFAULT 0;
ALTER TABLE call_details MODIFY lb_t_mos DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cardgroups MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cardgroups MODIFY setup_fee DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cardgroups MODIFY ghost_min_perc DECIMAL(30,15) DEFAULT 100;
ALTER TABLE cardgroups MODIFY daily_charge DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cardgroups MODIFY vat_percent DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cardgroups MODIFY ghost_balance_perc DECIMAL(30,15) DEFAULT 100;
ALTER TABLE cards MODIFY balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cards MODIFY frozen_balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cards MODIFY min_balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cc_gmps MODIFY percent DECIMAL(30,15) DEFAULT 100;
ALTER TABLE cclineitems MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE ccorders MODIFY amount DECIMAL(30,15) DEFAULT 0;
ALTER TABLE ccorders MODIFY fee DECIMAL(30,15) DEFAULT 0;
ALTER TABLE ccorders MODIFY gross DECIMAL(30,15) DEFAULT 0;
ALTER TABLE ccorders MODIFY tax DECIMAL(30,15) DEFAULT 0;
ALTER TABLE ccorders MODIFY tax_percent DECIMAL(30,15) DEFAULT 0;
ALTER TABLE credit_notes MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE credit_notes MODIFY price_with_vat DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cs_invoices MODIFY balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE cs_invoices MODIFY balance_with_tax DECIMAL(30,15) DEFAULT 0;
ALTER TABLE currencies MODIFY exchange_rate DECIMAL(30,15) DEFAULT 1;
ALTER TABLE devices MODIFY latency DECIMAL(30,15) DEFAULT 0;
ALTER TABLE didrates MODIFY rate DECIMAL(30,15) DEFAULT 0;
ALTER TABLE didrates MODIFY connection_fee DECIMAL(30,15) DEFAULT 0;
ALTER TABLE invoicedetails MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE invoices MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE invoices MODIFY price_with_vat DECIMAL(30,15) DEFAULT 0;
ALTER TABLE iplocations MODIFY latitude DECIMAL(30,15) DEFAULT 0;
ALTER TABLE iplocations MODIFY longitude DECIMAL(30,15) DEFAULT 0;
ALTER TABLE lcrs MODIFY first_provider_percent_limit DECIMAL(30,15) DEFAULT 0;
ALTER TABLE monitorings MODIFY amount DECIMAL(30,15) DEFAULT 0;
ALTER TABLE payments MODIFY amount DECIMAL(30,15) DEFAULT 0;
ALTER TABLE payments MODIFY fee DECIMAL(30,15) DEFAULT 0;
ALTER TABLE payments MODIFY gross DECIMAL(30,15) DEFAULT 0;
ALTER TABLE payments MODIFY tax DECIMAL(30,15) DEFAULT 0;
ALTER TABLE payments MODIFY vat_percent DECIMAL(30,15) DEFAULT 0;
ALTER TABLE providers MODIFY balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE ratedetails MODIFY rate DECIMAL(30,15) DEFAULT 0;
ALTER TABLE ratedetails MODIFY connection_fee DECIMAL(30,15) DEFAULT 0;
ALTER TABLE rates MODIFY ghost_min_perc DECIMAL(30,15) DEFAULT 0;
ALTER TABLE recordings MODIFY size DECIMAL(30,15) DEFAULT 0;
ALTER TABLE services MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE services MODIFY selfcost_price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE sms_messages MODIFY provider_rate DECIMAL(30,15) DEFAULT 0;
ALTER TABLE sms_messages MODIFY provider_price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE sms_messages MODIFY user_rate DECIMAL(30,15) DEFAULT 0;
ALTER TABLE sms_messages MODIFY user_price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE sms_messages MODIFY reseller_rate DECIMAL(30,15) DEFAULT 0;
ALTER TABLE sms_messages MODIFY reseller_price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE sms_rates MODIFY price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE taxes MODIFY tax1_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE taxes MODIFY tax2_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE taxes MODIFY tax3_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE taxes MODIFY tax4_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY calltime_normative DECIMAL(30,15) DEFAULT 3;
ALTER TABLE users MODIFY balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY frozen_balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY month_plan_perc DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY credit DECIMAL(30,15) DEFAULT -1;
ALTER TABLE users MODIFY vat_percent DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY c2c_call_price DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY tax_1 DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY tax_2 DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY tax_3 DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY tax_4 DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users MODIFY warning_email_balance DECIMAL(30,15) DEFAULT 0;
ALTER TABLE vouchers MODIFY credit_with_vat DECIMAL(30,15) DEFAULT 0;
ALTER TABLE vouchers MODIFY vat_percent DECIMAL(30,15) DEFAULT 0;
ALTER TABLE users ADD COLUMN responsible_accountant_id INT DEFAULT -1;
ALTER TABLE servers CHANGE server_type server_type ENUM('asterisk', 'sip_proxy');
CREATE TABLE IF NOT EXISTS server_devices (id INT UNSIGNED NOT NULL PRIMARY KEY, device_id INT UNSIGNED NOT NULL, server_id INT UNSIGNED NOT NULL) ENGINE=InnoDB  DEFAULT CHARSET=utf8;
CREATE INDEX device_server_index ON server_devices(device_id, server_id);
CREATE INDEX server_device_index ON server_devices(server_id, device_id);
ALTER TABLE server_devices MODIFY id int(10) unsigned NOT NULL auto_increment;
ALTER TABLE servers MODIFY server_type enum('asterisk','sip_proxy') NOT NULL DEFAULT 'asterisk';
ALTER TABLE devices ADD COLUMN tell_rate TINYINT DEFAULT 0 NOT NULL;
ALTER TABLE invoices ADD COLUMN tax_1_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN tax_2_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN tax_3_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN tax_4_value DECIMAL(30,15) DEFAULT 0;
ALTER TABLE invoices ADD COLUMN invoice_precision INT DEFAULT 2;
ALTER TABLE users MODIFY time_zone varchar(255) NOT NULL DEFAULT 'UTC';
ALTER TABLE devices ADD trunk enum('no','yes') DEFAULT 'no';
ALTER TABLE cron_settings ADD COLUMN lcr_id int(11) DEFAULT NULL;
ALTER TABLE `cards` CHANGE `first_use` `first_use` DATETIME NULL DEFAULT NULL;
ALTER TABLE `cards` CHANGE `daily_charge_paid_till` `daily_charge_paid_till` DATETIME NULL DEFAULT NULL;
CREATE UNIQUE INDEX uniqueidindex ON adnumbers (uniqueid);
ALTER TABLE devices MODIFY t38pt_udptl enum('no', 'yes', 'yes, fec', 'yes, redundancy', 'yes, none') default 'no';
ALTER TABLE devices ADD COLUMN proxy_port int(11) NOT NULL DEFAULT 0;
ALTER TABLE directions ADD COLUMN iso31661code VARCHAR(3) NOT NULL DEFAULT '000';
UPDATE addresses SET email = null WHERE email = ""; CREATE TEMPORARY TABLE temp_table AS (select email FROM addresses GROUP BY email HAVING count(*) > 1); UPDATE addresses INNER JOIN temp_table ON (addresses.email = temp_table.email) SET addresses.email = CONCAT(addresses.email,'_',addresses.id); DROP TABLE temp_table; CREATE UNIQUE INDEX unique_email ON addresses (email);
alter table users drop column c2c_service_active;
alter table users drop column c2c_call_price;
ALTER TABLE devices MODIFY COLUMN canreinvite ENUM('yes', 'no', 'nonat', 'update', 'update,nonat') DEFAULT 'no';
ALTER TABLE activecalls ENGINE=InnoDB;
ALTER TABLE cardgroups CHANGE pin_length pin_length INT(11) NOT NULL DEFAULT 6;
ALTER TABLE `devices` add `timerb` INT( 11 ) NULL DEFAULT NULL ;
ALTER TABLE devices MODIFY timerb INT(11) DEFAULT NULL;
UPDATE devices SET timerb=NULL; 
## SQL sentences goes to the top ^^^^^ from this line
# make sure you press ENTER (to end line) after last SQL sentence!
# also whole SQL sentence should go into one line
# ------------ DO NOT WRITE NOTHING PAST THIS LINE ---------------
