# DATA
# use this only when upgrading to mor9 for the first time or when user complains that he cannot see old calls
#UPDATE calls, devices SET dst_user_id = devices.user_id where calls.dst_device_id > 0 and devices.id = calls.dst_device_id;
#UPDATE calls, dids SET dst_user_id = dids.user_id where calls.did_id > 0 and dids.id = calls.did_id;
# removing the mark that DB is updated from script
DELETE FROM conflines WHERE name = 'DB_Update_From_Script';

INSERT INTO emails (name, template, date_created, subject, body, format) SELECT 'monitoring_activation', 1, NOW(),'Monitoring was activated',"Monitoring details:\n\nType: <%=monitoring_type%>\nBalance: <%=monitoring_amount%>\nBlock: <%=monitoring_block%>\n\nAffected users:\n\n<%=monitoring_users%>", "plain" FROM dual WHERE (SELECT COUNT(*) FROM emails WHERE name = 'monitoring_activation') = 0;

# upgrade main dial plan
DELETE FROM extlines WHERE context = 'mor' AND exten = '_X.';
INSERT INTO `extlines` (`context`, `exten`, `priority`, `app`, `appdata`, `device_id`) VALUES
    ('mor', '_X.', 1, 'NoOp', 'MOR starts', 0),
    ('mor', '_X.', 2, 'Set', 'TIMEOUT(response)=20', 0),
    ('mor', '_X.', 3, 'Set', 'TIMEOUT(digit)=10', 0),
    ('mor', '_X.', 4, 'mor', '${EXTEN}', 0),
    ('mor', '_X.', 5, 'GotoIf', '$["${MOR_CARD_USED}" != ""]?mor_callingcard|s|1', 0),
    ('mor', '_X.', 6, 'GotoIf', '$["${MOR_ANIPIN_USED}" != ""]?mor_anipin|s|1', 0),
    ('mor', '_X.', 7, 'GotoIf', '$["${MOR_TRUNK}" = "1"]?HANGUP_NOW|1', 0),
    ('mor', '_X.', 8, 'GotoIf', '$[$["${DIALSTATUS}" = "CHANUNAVAIL"] | $["${DIALSTATUS}" = "CONGESTION"]]?FAILED|1', 0),
    ('mor', '_X.', 9, 'GotoIf', '$["${DIALSTATUS}" = "BUSY"]?BUSY|1:HANGUP|1', 0)
;

DELETE FROM extlines WHERE context = 'mor' AND exten = 'HANGUP_NOW';
INSERT INTO `extlines` (`context`, `exten`, `priority`, `app`, `appdata`, `device_id`) VALUES
    ('mor', 'HANGUP_NOW', 1, 'Congestion', '1', 0),
    ('mor', 'HANGUP_NOW', 2, 'Hangup', '', 0)
;

DELETE FROM extlines WHERE context = 'mor' AND exten = 'HANGUP';
INSERT INTO `extlines` (`context`, `exten`, `priority`, `app`, `appdata`, `device_id`) VALUES
    ('mor', 'HANGUP', 1, 'Congestion', '1', 0),
    ('mor', 'HANGUP', 2, 'Hangup', '', 0)
;

DELETE FROM extlines WHERE context = 'mor' AND exten = 'FAILED';
INSERT INTO `extlines` (`context`, `exten`, `priority`, `app`, `appdata`, `device_id`) VALUES
    ('mor', 'FAILED', 1, 'Congestion', '1', 0),
    ('mor', 'FAILED', 2, 'Hangup', '', 0)
;


# update mailboxes for MWI
# not necessary by default, because generates sip 489 error
#UPDATE devices, voicemail_boxes SET devices.mailbox = CONCAT(voicemail_boxes.mailbox, "@", voicemail_boxes.context) WHERE devices.id = voicemail_boxes.device_id AND LENGTH(voicemail_boxes.mailbox) > 0;                                    

UPDATE users SET vat_percent = 0;

INSERT IGNORE INTO acc_rights (name,  nice_name, permission_group) VALUES ('user_manage', 'Manage_Users', 'User'), ('device_manage',      'Manage_Devices',     'Device'), ('see_financial_data', 'See_Financial_Data', 'Data'), ('vouchers_manage',    'Manage_Vouchers',    'Vouchers'), ('services_manage',    'Manage_Services',    'Services'), ('invoices_manage',    'Manage_Invoices',    'Invoices'), ('payments_manage',    'Manage_Payments',    'Payments');
INSERT IGNORE INTO acc_rights (name,  nice_name, permission_group) VALUES('monitorings_manage','Manage Monitorings','Monitorings');

# default languages-voices
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'silence',  'Silence files', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'silence') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'en',  'English voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'en') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'es',  'Spanish voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'es') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'ru',  'Russian voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'ru') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'fr',  'French voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'fr') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'zn',  'Chinese voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'zn') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'vn',  'Vietnamese voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'vn') = 0;

INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'pt_br',  'Brazilian-Portuguese voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'pt_br') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'it',  'Italian voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'it') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'de',  'German voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'de') = 0;
INSERT INTO ivr_voices (voice,description, created_at, readonly) SELECT 'he',  'Hebrew voice', '2010-05-01 00:00:00', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_voices WHERE voice= 'he') = 0;

# silence
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence1.wav', '1 second of silence', 16046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence1.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence2.wav', '2 seconds of silence', 32046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence2.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence3.wav', '3 seconds of silence', 48046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence3.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence4.wav', '4 seconds of silence', 64046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence4.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence5.wav', '5 seconds of silence', 80046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence5.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence6.wav', '6 seconds of silence', 96046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence6.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence7.wav', '7 seconds of silence', 112046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence7.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence8.wav', '8 seconds of silence', 128046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence8.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence9.wav', '9 seconds of silence', 144046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence9.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id,path, description, size, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'silence'),  'silence10.wav', '10 seconds of silence', 160046, 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE path= 'silence10.wav') = 0;

# english cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'en'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'en') AND path= 'cc_goodbye.wav') = 0;                      

# spanish cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'es'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'es') AND path= 'cc_goodbye.wav') = 0;

# french cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'fr'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'fr') AND path= 'cc_goodbye.wav') = 0;

# russian cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'ru'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'ru') AND path= 'cc_goodbye.wav') = 0;

# vietnamese cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'vn'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'vn') AND path= 'cc_goodbye.wav') = 0;

# chinese cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'zn'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'zn') AND path= 'cc_goodbye.wav') = 0;

# Brazilian-Portuguese cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'pt_br'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'pt_br') AND path= 'cc_goodbye.wav') = 0;

# Italian cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'it'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'it') AND path= 'cc_goodbye.wav') = 0;

# German cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'de'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'de') AND path= 'cc_goodbye.wav') = 0;

# Hebrew cc
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_enter_card_number_pin.wav', 'Please enter your card and pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_enter_card_number_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_enter_pin.wav', 'Please enter your pin number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_enter_pin.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_you_have_entered_nothing.wav', 'You have entered nothing', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_you_have_entered_nothing.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_card_not_found.wav', 'Card not found', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_card_not_found.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_card_expired.wav', 'Card expired', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_card_expired.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_card_is_not_sold_yet.wav', 'Card is not sold yet', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_card_is_not_sold_yet.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_card_is_empty.wav', 'Card is empty', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_card_is_empty.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_please_enter_number.wav', 'Please enter the number you wish to call', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_please_enter_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_busy.wav', 'The number is busy', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_busy.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_unreachable.wav', 'The number is unreachable', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_unreachable.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_callingcard_choices.wav', 'Press one to enter new number...', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_callingcard_choices.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_dialing_previous_number.wav', 'Dialing previous number', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_dialing_previous_number.wav') = 0;
INSERT INTO ivr_sound_files (ivr_voice_id, path, description, readonly) SELECT (SELECT id FROM ivr_voices WHERE voice = 'he'),  'cc_goodbye.wav', 'Goodbye', 1 FROM dual WHERE (SELECT COUNT(*) FROM ivr_sound_files WHERE ivr_voice_id = (SELECT id FROM ivr_voices WHERE voice = 'he') AND path= 'cc_goodbye.wav') = 0;
INSERT INTO acc_rights (name, nice_name, permission_group) SELECT 'cli_ivr', 'IVR', 'CLI' FROM dual WHERE (SELECT COUNT(*) FROM acc_rights WHERE name= 'cli_ivr') = 0;
INSERT INTO emails (name, template, date_created, subject, body, format) SELECT 'payment_notification_integrations', 1, NOW(), 'Payment notification', "MOR has received a payment notification which requires your confirmation in order to complete the transaction.<br/><br/>\n\nPayment details:<br/><br/>\n\nType: <%= payment_type %><br/>\nAmount: <%= payment_amount %><br/>\nFee: <%= payment_fee %><br/>\nPayer: <%= payment_payer_first_name %> <%= payment_payer_last_name %> <%= payment_payer_email %><br/>\nMoney should be sent to (your email in MOR): <%= payment_seller_email %><br/>\nMoney was sent to (according to gateway): <%= payment_receiver_email %><br/>\nDate: <%= payment_date %><br/><br/>\n\n<%= login_url %>/payments/list", "html" FROM dual WHERE (SELECT COUNT(*) FROM emails WHERE name = 'payment_notification_integrations') = 0;
INSERT INTO emails (name, template, date_created, subject, body, format) SELECT 'payment_notification_regular', 1, NOW(), 'Payment notification', "MOR has received a payment notification which requires your confirmation in order to complete the transaction.<br/><br/>\n\nPayment details:<br/><br/>\n\nType: <%= payment_type %><br/>\nAmount: <%= payment_amount %><br/>\nFee: <%= payment_fee %><br/>\nPayer: <%= payment_payer_first_name %> <%= payment_payer_last_name %>\n<br/>Date: <%= payment_date %><br/><br/>\n\n<%= login_url %>/payments/list", "html" FROM dual WHERE (SELECT COUNT(*) FROM emails WHERE name = 'payment_notification_regular') = 0;
UPDATE conflines SET value = 'MOR 9' WHERE value = 'MOR 8' AND name = 'Admin_Browser_Title';
UPDATE conflines SET value = 'MOR 9' WHERE value = 'MOR 8' AND name = 'Version';
update currencies set exchange_rate = 1 where id = 1;
UPDATE users SET blocked = 1 WHERE id = 2;
# pbxfunction
INSERT INTO pbxfunctions (name, pf_type, context, extension, priority) SELECT 'Current Time',  'current_time', 'mor_pbxfunctions', 'current_time', 1 FROM dual WHERE (SELECT COUNT(*) FROM pbxfunctions WHERE name = 'Current Time') = 0;
INSERT INTO currencies (name, full_name, active) SELECT 'KZT', 'Kazakhstani Tenge', 0 FROM dual WHERE (SELECT COUNT(*) FROM currencies WHERE name = 'KZT' ) = 0;
INSERT INTO emails (`name`, `format`, `body`, `owner_id`, `subject`, `template`, `callcenter`, `date_created`) SELECT 'password_reminder', 'html', 'Settings to login to MOR interface:  Login URL: <%= login_url %> Username: <%= login_username %> Password: <%= login_password %>', 0, 'password_reminder', 1, 0, NOW() FROM dual WHERE (SELECT COUNT(*) FROM emails WHERE name = 'password_reminder' AND owner_id = 0) = 0;
INSERT INTO pbxfunctions (name, pf_type, context, extension, priority) SELECT 'External DID', 'external_did', 'mor_pbxfunctions', 'external_did', 1 FROM dual WHERE (SELECT COUNT(*) FROM pbxfunctions WHERE name = 'External DID') = 0;
UPDATE conflines SET value = 1 WHERE name = 'Default_device_works_not_logged';
UPDATE devices SET context = 'mor_local' WHERE context = 'please_login';
UPDATE devices SET works_not_logged = 1;
INSERT INTO conflines(name, value, owner_id) SELECT 'Invoice_page_limit', '20', '0' FROM DUAL WHERE (SELECT COUNT(*) FROM conflines WHERE name = 'Invoice_page_limit' AND owner_id = 0) = 0; 
INSERT INTO conflines(name, value, owner_id) SELECT 'Prepaid_Invoice_page_limit', '20', '0' FROM DUAL WHERE (SELECT COUNT(*) FROM conflines WHERE name = 'Prepaid_Invoice_page_limit' AND owner_id = 0) = 0;
update emails set body =  0x596f7572206465766963652073657474696e67733a200d0a0d0a5365727665722049503a203c253d207365727665725f697020253e0d0a44657669636520747970653a203c253d206465766963655f7479706520253e0d0a557365726e616d653a203c253d206465766963655f757365726e616d6520253e0d0a50617373776f72643a203c253d206465766963655f70617373776f726420253e0d0a0d0a2d2d2d2d0d0a0d0a53657474696e677320746f206c6f67696e20746f204d4f5220696e746572666163653a0d0a0d0a4c6f67696e2055524c3a203c253d206c6f67696e5f75726c20253e0d0a557365726e616d653a203c253d206c6f67696e5f757365726e616d6520253e0d0a50617373776f72643a203c253d206c6f67696e5f70617373776f726420253e0d0a0d0a5468616e6b20796f7520666f72207265676973746572696e6721 where body = 0x596f75206465766963652073657474696e67733a200d0a0d0a5365727665722049503a203c253d207365727665725f697020253e0d0a44657669636520747970653a203c253d206465766963655f7479706520253e0d0a557365726e616d653a203c253d206465766963655f757365726e616d6520253e0d0a50617373776f72643a203c253d206465766963655f70617373776f726420253e0d0a0d0a2d2d2d2d0d0a0d0a53657474696e677320746f206c6f67696e20746f204d4f5220696e746572666163653a0d0a0d0a4c6f67696e2055524c3a203c253d206c6f67696e5f75726c20253e0d0a557365726e616d653a203c253d206c6f67696e5f757365726e616d6520253e0d0a50617373776f72643a203c253d206c6f67696e5f70617373776f726420253e0d0a0d0a5468616e6b20796f7520666f72207265676973746572696e6721;
update conflines set value="" where name = 'WebMoney_Purse' and value = "Z616776332783";
INSERT INTO conflines(name, value, owner_id) SELECT 'Disalow_Duplicate_Device_Usernames', 1, 0 FROM DUAL WHERE (SELECT COUNT(*) FROM conflines WHERE name = 'Disalow_Duplicate_Device_Usernames' AND owner_id = 0) = 0;
UPDATE conflines set value = '' WHERE name = 'Last_Crash_Exception_Class';
UPDATE devices SET insecure = NULL WHERE id = 2;

# ^^^^^^ WRITE ABOVE THIS LINE ^^^^^
# marking that DB is updated from script
INSERT INTO conflines (name, value) VALUES ('DB_Update_From_Script', 1);
