ALTER TABLE providers ADD COLUMN periodic_check TINYINT default 0;
ALTER TABLE alerts ADD COLUMN clear_after INT(10) unsigned default 0;
ALTER TABLE numbers CONVERT TO CHARACTER SET utf8;
ALTER TABLE number_pools CONVERT TO CHARACTER SET utf8;
ALTER TABLE alerts ADD COLUMN enable_provider_in_lcr tinyint(3) unsigned NOT NULL default 0;
ALTER TABLE alerts ADD COLUMN disable_provider_in_lcr tinyint(3) unsigned NOT NULL default 0;
ALTER TABLE dids ADD COLUMN owner_tariff_id int(11) NOT NULL DEFAULT 0;
ALTER TABLE acc_permissions CONVERT TO CHARACTER SET utf8;
ALTER TABLE bl_dst_new_score CONVERT TO CHARACTER SET utf8;
ALTER TABLE bl_dst_scoring CONVERT TO CHARACTER SET utf8;
ALTER TABLE bl_ip_new_score CONVERT TO CHARACTER SET utf8;
ALTER TABLE bl_ip_scoring CONVERT TO CHARACTER SET utf8;
ALTER TABLE bl_src_new_score CONVERT TO CHARACTER SET utf8;
ALTER TABLE bl_src_scoring CONVERT TO CHARACTER SET utf8;
CREATE TABLE IF NOT EXISTS `blanks` (`id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT, `name` VARCHAR(255), `date` DATETIME, `description` TEXT, `value1` INT, `value2` DECIMAL(8,4), `value3` ENUM('yes', 'no') DEFAULT 'no') ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS active_calls_data (   id INT(11) AUTO_INCREMENT,   time timestamp,   count INT(10),   PRIMARY KEY(id),   INDEX USING BTREE(time) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS pbx_pools (id INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT, name VARCHAR(255), comment TEXT, owner_id INT(11)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE users ADD COLUMN pbx_pool_id int(11) NOT NULL DEFAULT 0;
ALTER TABLE devices MODIFY transport enum('udp','tcp','udp,tcp','tcp,udp','tls') default 'udp';
ALTER TABLE cron_settings ADD COLUMN inv_from SMALLINT DEFAULT NULL;
ALTER TABLE cron_settings ADD COLUMN inv_till SMALLINT DEFAULT NULL;
ALTER TABLE cron_settings ADD COLUMN inv_issue_day SMALLINT DEFAULT NULL;
ALTER TABLE cron_settings ADD COLUMN inv_send_after TINYINT DEFAULT NULL;
ALTER TABLE rates ADD COLUMN effective_from DATETIME DEFAULT NULL;
CREATE TABLE IF NOT EXISTS `routing_groups` (`id` int(11) NOT NULL AUTO_INCREMENT, `name` varchar(100) NOT NULL, `comment` varchar(255) NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
CREATE TABLE IF NOT EXISTS `rgroup_dpeers` (`id` int UNSIGNED NOT NULL AUTO_INCREMENT, `routing_group_id` INT UNSIGNED NOT NULL, `dial_peer_id` INT UNSIGNED NOT NULL, `dial_peer_priority` INT UNSIGNED NOT NULL DEFAULT 1, PRIMARY KEY (`id`), INDEX `rgroup_dpeer_index` (`routing_group_id` ASC, `dial_peer_id` ASC)) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE users ADD COLUMN hide_non_answered_calls TINYINT NOT NULL DEFAULT 0;
ALTER TABLE devices ADD COLUMN op TINYINT UNSIGNED NOT NULL DEFAULT 0,ADD COLUMN op_active TINYINT UNSIGNED NOT NULL DEFAULT 0,ADD COLUMN op_tech_prefix VARCHAR(50) NOT NULL DEFAULT '',ADD COLUMN op_routing_algorithm ENUM('lcr','quality','profit','weight','percent') NOT NULL DEFAULT 'lcr',ADD COLUMN op_routing_group_id INT UNSIGNED NOT NULL DEFAULT 0,ADD COLUMN op_tariff_id INT UNSIGNED NOT NULL DEFAULT 0,ADD COLUMN op_capacity INT UNSIGNED NOT NULL DEFAULT 500,ADD COLUMN op_src_regexp VARCHAR(255) NOT NULL DEFAULT '',ADD COLUMN op_src_deny_regexp VARCHAR(255) NOT NULL DEFAULT '',ADD COLUMN tp TINYINT UNSIGNED NOT NULL DEFAULT 0,ADD COLUMN tp_active TINYINT UNSIGNED NOT NULL DEFAULT 0,ADD COLUMN tp_tech_prefix VARCHAR(50) NOT NULL DEFAULT '',ADD COLUMN tp_tariff_id INT UNSIGNED NOT NULL DEFAULT 0,ADD COLUMN tp_capacity INT UNSIGNED NOT NULL DEFAULT 500,ADD COLUMN tp_src_regexp VARCHAR(255) NOT NULL DEFAULT '',ADD COLUMN tp_src_deny_regexp VARCHAR(255) NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS dpeer_tpoints (id INT UNSIGNED NOT NULL AUTO_INCREMENT,dial_peer_id INT UNSIGNED NOT NULL,device_id INT UNSIGNED NOT NULL,tp_percent INT UNSIGNED NOT NULL DEFAULT 100,tp_weight INT UNSIGNED NOT NULL DEFAULT 1,PRIMARY KEY (id),INDEX dial_peer_index USING BTREE (dial_peer_id ASC))ENGINE = InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS dial_peers (id INT UNSIGNED NOT NULL AUTO_INCREMENT,    active TINYINT UNSIGNED NOT NULL DEFAULT 1,    name VARCHAR(100) NOT NULL,    comment VARCHAR(255) NOT NULL,    dst_regexp VARCHAR(255) NOT NULL,    dst_deny_regexp VARCHAR(255) NOT NULL,    src_regexp VARCHAR(255) NOT NULL,    src_deny_regexp VARCHAR(255) NOT NULL,    weight INT UNSIGNED NOT NULL DEFAULT 1,    stop_hunting TINYINT UNSIGNED NOT NULL DEFAULT 1,    delta_price DECIMAL(8,4) NOT NULL DEFAULT 0,    tp_priority ENUM('weight','percent') NOT NULL DEFAULT 'weight',    PRIMARY KEY (id)) ENGINE = InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE invoices ADD COLUMN invoice_exchange_rate decimal(30,15) DEFAULT 1;
ALTER TABLE invoices ADD COLUMN invoice_currency varchar(255);
ALTER TABLE alerts MODIFY disable_provider_in_lcr INT(11) NOT NULL DEFAULT 0;
ALTER TABLE callerids DROP FOREIGN KEY device_id;
ALTER TABLE users  ADD COLUMN balance_min DECIMAL(10,4) DEFAULT 0;
ALTER TABLE users  ADD COLUMN balance_max DECIMAL(10,4) DEFAULT 0;
ALTER TABLE `dids` CHANGE `id` `id` BIGINT( 11 ) UNSIGNED NOT NULL AUTO_INCREMENT;
CREATE TABLE IF NOT EXISTS `m2_payments` (`id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT, `user_id` INT(11) UNSIGNED DEFAULT NULL, `comment` varchar(255) DEFAULT NULL, `date` DATETIME DEFAULT NULL, `amount` decimal(30,15) DEFAULT '0.000000000000000', `amount_with_tax` decimal(30,15) DEFAULT '0.000000000000000', `currency_id` INT(11) UNSIGNED NOT NULL DEFAULT 1, `exchange_rate` decimal(30,15) NOT NULL DEFAULT 1, PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE blanks ADD balance decimal(30,15) NOT NULL DEFAULT '0.0000';
ALTER TABLE users ADD COLUMN main_email VARCHAR(50);
ALTER TABLE users ADD COLUMN noc_email VARCHAR(50);
ALTER TABLE users ADD COLUMN billing_email VARCHAR(50);
ALTER TABLE users ADD COLUMN rates_email VARCHAR(50);
ALTER TABLE users ADD COLUMN warning_email_balance_admin decimal(30,15) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN warning_email_balance_manager decimal(30,15) NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN `billing_period` ENUM ('weekly', 'bi-weekly', 'monthly') NOT NULL DEFAULT 'monthly';
ALTER TABLE users ADD COLUMN `invoice_grace_period` TINYINT(3) NOT NULL DEFAULT 15;
ALTER TABLE alerts ADD COLUMN clear_on_date DATETIME DEFAULT NULL;
ALTER TABLE users ADD COLUMN warning_email_sent_admin tinyint(4) DEFAULT 0;
ALTER TABLE users ADD COLUMN warning_email_sent_manager tinyint(4) DEFAULT 0;
CREATE TABLE IF NOT EXISTS `aggregates` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT,`uniqueid` bigint(11) unsigned NOT NULL DEFAULT 0, `direction` varchar(255) DEFAULT NULL, `destination` varchar(255) DEFAULT NULL, `prefix` varchar(255) DEFAULT NULL, `terminator_id` int(11) DEFAULT NULL, `user_id` int(11) DEFAULT NULL, `reseller_id` int(11) DEFAULT NULL, `time_period_id` int(11) NOT NULL DEFAULT 0, `user_billed` decimal(30,15) DEFAULT '0.000000000000000', `user_billed_with_tax` decimal(30,15) DEFAULT '0.000000000000000', `terminator_billed` decimal(30,15) DEFAULT '0.000000000000000', `user_billed_billsec` int(11) NOT NULL DEFAULT '0', `terminator_billed_billsec` int(11) NOT NULL DEFAULT '0', `billsec` int(11) NOT NULL DEFAULT '0', `real_billsec` decimal(30,15) DEFAULT '0.000000000000000',`answered_calls` int(11) NOT NULL DEFAULT '0', `total_calls` int(11) NOT NULL DEFAULT '0', `total_calls_for_user` int(11) NOT NULL DEFAULT '0', `variation` int(11) NOT NULL, PRIMARY KEY (`id`), UNIQUE KEY `id` (`id`),UNIQUE KEY `uniqueid` (`uniqueid`), KEY `time_period_id_index` (`time_period_id`), KEY `user_id_index` (`user_id`), KEY `terminator_id_index` (`terminator_id`), KEY `reseller_id_index` (`reseller_id`), KEY `variation_index` (`variation`), KEY `prefix_index` (`prefix`(4)), KEY `direction_index` (`direction`), KEY `destination_index` (`destination`(6)) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `time_periods` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT,`from_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00', `period_type` enum('hour', 'day', 'month', 'year'), PRIMARY KEY (`id`), KEY `from_date_index` (`from_date`),UNIQUE KEY `id` (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
#CREATE TABLE `m2_invoices` (`id` SERIAL, `number` VARCHAR(255) NOT NULL, `user_id` INT(11) UNSIGNED DEFAULT NULL, `status` ENUM ('In process', 'Sent through Email', 'Sent Manually', 'Accepted', 'Protested', 'Paid', 'Closed', 'Deleted', 'Changed')  NOT NULL DEFAULT 'In process', `status_changed` DATETIME NOT NULL, `created_at` DATETIME NOT NULL, `updated_at` DATETIME, `issue_date` DATETIME, `period_start` DATETIME NOT NULL, `period_end` DATETIME NOT NULL, `due_date` DATETIME, `timezone` VARCHAR(255) NOT NULL DEFAULT 'UTC', `client_name` VARCHAR(255) DEFAULT NULL, `client_details1` VARCHAR(255) DEFAULT NULL, `client_details2` VARCHAR(255) DEFAULT NULL, `client_details3` VARCHAR(255) DEFAULT NULL, `client_details4` VARCHAR(255) DEFAULT NULL, `client_details5` VARCHAR(255) DEFAULT NULL, `client_details6` VARCHAR(255) DEFAULT NULL, `currency` VARCHAR(50) NOT NULL DEFAULT 'eur', `currency_exchange_rate` DECIMAL(30,15), `total_amount` DECIMAL(30,15) DEFAULT '0.000000000000000', `total_amount_with_taxes` DECIMAL(30,15) DEFAULT '0.000000000000000', `comment` TEXT, `mailed_to_user` TINYINT(1) UNSIGNED DEFAULT NULL, `notified_admin` TINYINT(1) UNSIGNED DEFAULT NULL, `notified_manager` TINYINT(1) UNSIGNED DEFAULT NULL, PRIMARY KEY  (`id`), KEY `period_start_index` (`period_start`)) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
#CREATE TABLE `m2_invoice_lines` ( `id` SERIAL, `m2_invoice_id` INT(11) UNSIGNED DEFAULT NULL, `destination` VARCHAR(50) DEFAULT NULL, `name` VARCHAR(255) DEFAULT NULL, `rate` DECIMAL(30,15) DEFAULT '1.000000000000000', `calls` INT(50) UNSIGNED DEFAULT NULL, `total_time` INT(50) UNSIGNED DEFAULT NULL, `price` DECIMAL(30,15) DEFAULT '0.000000000000000', PRIMARY KEY  (`id`), KEY `m2_invoice_id_index` (`m2_invoice_id`)) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
ALTER TABLE users ADD COLUMN comment text;
ALTER TABLE `dial_peers` CHANGE `delta_price` `delta_price` DECIMAL(30,15) NOT NULL DEFAULT 0.000000000000000;
ALTER TABLE users ADD column routing_threshold_2 INT(11) NOT NULL DEFAULT -1;
ALTER TABLE users ADD column blacklist_lcr_2 INT(11) NOT NULL DEFAULT -1;
ALTER TABLE users ADD column routing_threshold_3 INT(11) NOT NULL DEFAULT -1;
ALTER TABLE users ADD column blacklist_lcr_3 INT(11) NOT NULL DEFAULT -1;
CREATE TABLE IF NOT EXISTS `timezones` (`id` int(11) NOT NULL AUTO_INCREMENT, `zone` varchar(100) NOT NULL UNIQUE, `offset` int(11) NOT NULL, PRIMARY KEY (`id`), KEY `zone_index` (`zone`(4))) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE `dids` ADD COLUMN `external_server` VARCHAR(50);
ALTER TABLE alerts ADD COLUMN notify_to_user INT(11) NOT NULL DEFAULT 0;
ALTER TABLE devices ADD COLUMN copy_name_to_number TINYINT(3) unsigned DEFAULT 0;
ALTER TABLE alerts ADD COLUMN hgc INT(11) NOT NULL DEFAULT 0;
CREATE TABLE IF NOT EXISTS `alert_dependencies` ( `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT, `owner_alert_id` bigint(20) unsigned NOT NULL, `alert_id` bigint(20) unsigned NOT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
ALTER TABLE alerts MODIFY COLUMN alert_type ENUM('asr','acd','pdd','ttc','billsec_sum','calls_total','calls_answered','calls_not_answered','price_sum','sim_calls','hgc_absolute','hgc_percent', 'group');
ALTER TABLE alerts ADD COLUMN alert_when_more_than int(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE alerts ADD COLUMN clear_when_less_than int(11) UNSIGNED NOT NULL DEFAULT '0';
ALTER TABLE alerts ADD COLUMN name varchar(30) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN ignore_global_alerts TINYINT DEFAULT 0;
ALTER TABLE numbers ADD INDEX ( number , number_pool_id );
ALTER TABLE devices ADD COLUMN custom_sip_header VARCHAR(255) DEFAULT NULL;
ALTER TABLE `conflines` ADD INDEX ( `name` ( 10 ) , `owner_id` );
ALTER TABLE servers DROP COLUMN server_id;
ALTER TABLE groups ADD COLUMN simple_session SMALLINT NOT NULL default 0;
ALTER TABLE groups ADD COLUMN postpaid  SMALLINT NOT NULL default 0;
ALTER TABLE groups ADD COLUMN balance  decimal(30,15) NOT NULL DEFAULT '0.0000';
ALTER TABLE groups MODIFY postpaid SMALLINT NOT NULL default -1;
ALTER TABLE dialplans ADD COLUMN data13 VARCHAR(255) DEFAULT NULL;
# fixes to aggregate table after upgrade from x4 where it is messed up
ALTER TABLE `aggregates` CHANGE `tp_user_id` `terminator_id` INT( 11 ) NULL DEFAULT '0';
ALTER TABLE `aggregates` CHANGE `op_user_id` `user_id` INT( 11 ) NULL DEFAULT '0' ;
ALTER TABLE `aggregates` CHANGE `op_user_billed` `user_billed` DECIMAL( 30, 15 ) NULL DEFAULT '0.000000000000000';
ALTER TABLE `aggregates` CHANGE `op_user_billed_with_tax` `user_billed_with_tax` DECIMAL( 30, 15 ) NULL DEFAULT '0.000000000000000';
ALTER TABLE `aggregates` CHANGE `tp_user_billed` `terminator_billed` DECIMAL( 30, 15 ) NULL DEFAULT '0.000000000000000' ;
ALTER TABLE `aggregates` CHANGE `op_user_billed_billsec` `user_billed_billsec` INT( 11 ) NOT NULL DEFAULT '0' ;
ALTER TABLE `aggregates` CHANGE `tp_user_billed_billsec` `terminator_billed_billsec` INT( 11 ) NOT NULL DEFAULT '0';
ALTER TABLE tariffs ADD COLUMN last_update_date datetime DEFAULT NULL;
ALTER TABLE devices ADD COLUMN comment text;
ALTER TABLE servers MODIFY COLUMN server_type enum ('asterisk', 'sip_proxy', 'other') NOT NULL DEFAULT 'asterisk';
ALTER TABLE callflows ADD data5 INTEGER;
ALTER TABLE addresses DROP INDEX unique_email;
ALTER TABLE time_periods ADD COLUMN last_call_id BIGINT(11) UNSIGNED DEFAULT NULL;
ALTER TABLE devices ADD inherit_codec int(11) DEFAULT NULL;
CREATE TABLE IF NOT EXISTS `call_details_old` (`id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,`call_id` bigint(20) DEFAULT NULL,`pdd` decimal(30,15) DEFAULT '0.000000000000000',`la_ip` int(11) DEFAULT NULL,`la_local_ip` int(11) DEFAULT NULL,`la_codec` int(11) DEFAULT NULL,`la_rtt` decimal(30,15) DEFAULT '0.000000000000000',`la_r` int(11) DEFAULT NULL,`la_mos` decimal(30,15) DEFAULT '0.000000000000000',`la_rxcount` int(11) DEFAULT NULL,`la_lp` int(11) DEFAULT NULL,`la_rxjitter` decimal(30,15) DEFAULT '0.000000000000000',`la_r_r` int(11) DEFAULT NULL,`la_r_mos` decimal(30,15) DEFAULT '0.000000000000000',`la_tx_count` int(11) DEFAULT NULL,`la_rlp` int(11) DEFAULT NULL,`la_txjitter` decimal(30,15) DEFAULT '0.000000000000000',`la_t_r` int(11) DEFAULT NULL,`la_t_mos` decimal(30,15) DEFAULT '0.000000000000000',`lb_ip` int(11) DEFAULT NULL,`lb_local_ip` int(11) DEFAULT NULL,`lb_codec` tinyint(4) DEFAULT NULL,`lb_rtt` decimal(30,15) DEFAULT '0.000000000000000',`lb_r` int(11) DEFAULT NULL,`lb_mos` decimal(30,15) DEFAULT '0.000000000000000',`lb_rxcount` int(11) DEFAULT NULL,`lb_lp` int(11) DEFAULT NULL,`lb_rxjitter` decimal(30,15) DEFAULT '0.000000000000000',`lb_r_r` int(11) DEFAULT NULL,`lb_r_mos` decimal(30,15) DEFAULT '0.000000000000000',`lb_txcount` int(11) DEFAULT NULL,`lb_rlp` int(11) DEFAULT NULL,`lb_txjitter` decimal(30,15) DEFAULT '0.000000000000000',`lb_t_r` int(11) DEFAULT NULL,`lb_t_mos` decimal(30,15) DEFAULT '0.000000000000000',`peerip` int(10) unsigned DEFAULT NULL,`recvip` int(10) unsigned DEFAULT NULL,`sipfrom` varchar(255) DEFAULT NULL,`uri` varchar(255) DEFAULT NULL,`useragent` varchar(255) DEFAULT NULL,`peername` varchar(255) DEFAULT NULL,`t38passthrough` tinyint(4) DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;
ALTER TABLE calls ADD `dst_user_id` int(11) DEFAULT NULL COMMENT 'users id which receives call';
ALTER TABLE users ADD COLUMN enable_static_list enum('no', 'blacklist', 'whitelist') NOT NULL DEFAULT 'no';
ALTER TABLE users ADD static_list_id int(11) DEFAULT NULL;
## SQL sentences goes to the top ^^^^^ from this line
# make sure you press ENTER (to end line) after last SQL sentence!
# also whole SQL sentence should go into one line
# marking that DB is updated from script
