use mor;

INSERT INTO `destinationgroups` (`id`, `name`, `desttype`, `flag`) VALUES 
(1, 'Afghanistan', 'FIX', 'afg'),
(2, 'Afghanistan', 'MOB', 'afg'),
(3, 'Albania', 'FIX', 'alb'),
(4, 'Albania', 'MOB', 'alb'),
(5, 'Algeria', 'FIX', 'dza'),
(6, 'Algeria', 'MOB', 'dza'),
(7, 'American Samoa', 'FIX', 'asm'),
(8, 'American Samoa', 'MOB', 'asm'),
(9, 'Andorra', 'FIX', 'and'),
(10, 'Andorra', 'MOB', 'and'),
(11, 'Angola', 'FIX', 'ago'),
(12, 'Angola', 'MOB', 'ago'),
(13, 'Anguilla', 'FIX', 'aia'),
(14, 'Anguilla', 'MOB', 'aia'),
(15, 'Antarctica', 'FIX', 'ata'),
(16, 'Antigua And Barbuda', 'FIX', 'atg'),
(17, 'Argentina', 'FIX', 'arg'),
(18, 'Argentina', 'MOB', 'arg'),
(19, 'Armenia', 'FIX', 'arm'),
(20, 'Armenia', 'MOB', 'arm'),
(21, 'Aruba', 'FIX', 'abw'),
(22, 'Aruba', 'MOB', 'abw'),
(23, 'Ascension Island', 'FIX', 'asc'),
(24, 'Australia', 'FIX', 'aus'),
(25, 'Australia', 'MOB', 'aus'),
(26, 'Austria', 'FIX', 'aut'),
(27, 'Austria', 'MOB', 'aut'),
(28, 'Austria', 'NGN', 'aut'),
(29, 'Azerbaijan', 'FIX', 'aze'),
(30, 'Azerbaijan', 'MOB', 'aze'),
(31, 'Antigua And Barbuda', 'MOB', 'atg'),
(32, 'Bahamas', 'FIX', 'bhs'),
(33, 'Bahamas', 'MOB', 'bhs'),
(34, 'Bahrain', 'FIX', 'bhr'),
(35, 'Bahrain', 'MOB', 'bhr'),
(36, 'Bahrain', 'NGN', 'bhr'),
(37, 'Bangladesh', 'FIX', 'bgd'),
(38, 'Bangladesh', 'MOB', 'bgd'),
(39, 'Bangladesh', 'NGN', 'bgd'),
(40, 'Barbados', 'FIX', 'brb'),
(41, 'Barbados', 'MOB', 'brb'),
(42, 'Belarus', 'FIX', 'blr'),
(43, 'Belarus', 'MOB', 'blr'),
(44, 'Belgium', 'FIX', 'bel'),
(45, 'Belgium', 'MOB', 'bel'),
(46, 'Belgium', 'NGN', 'bel'),
(47, 'Belize', 'FIX', 'blz'),
(48, 'Belize', 'MOB', 'blz'),
(49, 'Benin', 'FIX', 'ben'),
(50, 'Benin', 'MOB', 'ben'),
(51, 'Bermuda', 'FIX', 'bmu'),
(52, 'Bermuda', 'MOB', 'bmu'),
(53, 'Bhutan', 'FIX', 'btn'),
(54, 'Bhutan', 'MOB', 'btn'),
(55, 'Bolivia', 'FIX', 'bol'),
(56, 'Bolivia', 'MOB', 'bol'),
(57, 'Bosnia And Herzegovina', 'FIX', 'bih'),
(58, 'Bosnia And Herzegovina', 'MOB', 'bih'),
(59, 'Botswana', 'FIX', 'bwa'),
(60, 'Botswana', 'MOB', 'bwa'),
(61, 'Brazil', 'FIX', 'bra'),
(62, 'Brazil', 'MOB', 'bra'),
(63, 'Brunei Darussalam', 'FIX', 'brn'),
(64, 'Brunei Darussalam', 'MOB', 'brn'),
(65, 'Bulgaria', 'FIX', 'bgr'),
(66, 'Bulgaria', 'MOB', 'bgr'),
(67, 'Burkina Faso', 'FIX', 'bfa'),
(68, 'Burkina Faso', 'MOB', 'bfa'),
(69, 'Burundi', 'FIX', 'bdi'),
(70, 'Burundi', 'MOB', 'bdi'),
(71, 'Cambodia', 'FIX', 'khm'),
(72, 'Cambodia', 'MOB', 'khm'),
(73, 'Cameroon', 'FIX', 'cmr'),
(74, 'Cameroon', 'MOB', 'cmr'),
(75, 'Canada', 'FIX', 'can'),
(76, 'Cape Verde', 'FIX', 'cpv'),
(77, 'Cape Verde', 'MOB', 'cpv'),
(78, 'Cayman Islands', 'FIX', 'cym'),
(79, 'Cayman Islands', 'MOB', 'cym'),
(80, 'Central African Republic', 'FIX', 'caf'),
(81, 'Chad', 'FIX', 'tcd'),
(82, 'Chad', 'MOB', 'tcd'),
(83, 'Chile', 'FIX', 'chl'),
(84, 'Chile', 'MOB', 'chl'),
(85, 'China', 'FIX', 'chn'),
(86, 'China', 'MOB', 'chn'),
(87, 'Christmas Island', 'FIX', 'cxr'),
(88, 'Cocos (Keeling) Islands', 'FIX', 'cck'),
(89, 'Colombia', 'FIX', 'col'),
(90, 'Colombia', 'MOB', 'col'),
(91, 'Comoros', 'FIX', 'com'),
(92, 'Comoros', 'MOB', 'com'),
(93, 'Congo', 'FIX', 'cog'),
(94, 'Congo', 'MOB', 'cog'),
(95, 'Congo, The Democratic Republic Of The', 'FIX', 'cod'),
(96, 'Congo, The Democratic Republic Of The', 'MOB', 'cod'),
(97, 'Cook Islands', 'FIX', 'cok'),
(98, 'Cook Islands', 'MOB', 'cok'),
(99, 'Costa Rica', 'FIX', 'cri'),
(100, 'Costa Rica', 'MOB', 'cri'),
(101, 'Ivory Coast', 'FIX', 'civ'),
(102, 'Ivory Coast', 'MOB', 'civ'),
(103, 'Croatia', 'FIX', 'hrv'),
(104, 'Croatia', 'MOB', 'hrv'),
(105, 'Croatia', 'NGN', 'hrv'),
(106, 'Cuba', 'FIX', 'cub'),
(107, 'Cyprus', 'FIX', 'cyp'),
(108, 'Cyprus', 'MOB', 'cyp'),
(109, 'Cyprus', 'NGN', 'cyp'),
(110, 'Czech Republic', 'FIX', 'cze'),
(111, 'Czech Republic', 'MOB', 'cze'),
(112, 'Denmark', 'FIX', 'dnk'),
(113, 'Denmark', 'MOB', 'dnk'),
(114, 'Denmark', 'NGN', 'dnk'),
(115, 'Diego Garcia', 'FIX', 'dga'),
(116, 'Djibouti', 'FIX', 'dji'),
(117, 'Djibouti', 'MOB', 'dji'),
(118, 'Dominica', 'FIX', 'dma'),
(119, 'Dominica', 'MOB', 'dma'),
(120, 'Dominican Republic', 'FIX', 'dom'),
(121, 'Dominican Republic', 'MOB', 'dom'),
(122, 'East Timor', 'FIX', 'tmp'),
(123, 'East Timor', 'MOB', 'tmp'),
(124, 'Ecuador', 'FIX', 'ecu'),
(125, 'Ecuador', 'MOB', 'ecu'),
(126, 'Egypt', 'FIX', 'egy'),
(127, 'Egypt', 'MOB', 'egy'),
(128, 'El Salvador', 'FIX', 'slv'),
(129, 'El Salvador', 'MOB', 'slv'),
(130, 'Ellipso-3', 'NGN', 'el3'),
(131, 'Emsat', 'NGN', 'ems'),
(132, 'Equatorial Guinea', 'FIX', 'gnq'),
(133, 'Equatorial Guinea', 'MOB', 'gnq'),
(134, 'Eritrea', 'FIX', 'eri'),
(135, 'Estonia', 'FIX', 'est'),
(136, 'Estonia', 'MOB', 'est'),
(137, 'Ethiopia', 'FIX', 'eth'),
(138, 'Ethiopia', 'MOB', 'eth'),
(139, 'Falkland Islands (Malvinas)', 'FIX', 'flk'),
(140, 'Faroe Islands', 'FIX', 'fro'),
(141, 'Faroe Islands', 'MOB', 'fro'),
(142, 'Fiji', 'FIX', 'fji'),
(143, 'Fiji', 'MOB', 'fji'),
(144, 'Finland', 'FIX', 'fin'),
(145, 'Finland', 'MOB', 'fin'),
(146, 'Finland', 'NGN', 'fin'),
(147, 'France', 'FIX', 'fra'),
(148, 'France', 'MOB', 'fra'),
(149, 'France', 'NGN', 'fra'),
(150, 'French Guiana', 'FIX', 'guf'),
(151, 'French Guiana', 'MOB', 'guf'),
(152, 'French Polynesia', 'FIX', 'pyf'),
(153, 'French Polynesia', 'MOB', 'pyf'),
(154, 'Gabon', 'FIX', 'gab'),
(155, 'Gabon', 'MOB', 'gab'),
(156, 'Gambia', 'FIX', 'gmb'),
(157, 'Gambia', 'MOB', 'gmb'),
(158, 'Georgia', 'FIX', 'geo'),
(159, 'Georgia', 'MOB', 'geo'),
(160, 'Germany', 'FIX', 'deu'),
(161, 'Germany', 'MOB', 'deu'),
(162, 'Germany', 'NGN', 'deu'),
(163, 'Ghana', 'FIX', 'gha'),
(164, 'Ghana', 'MOB', 'gha'),
(165, 'Gibraltar', 'FIX', 'gib'),
(166, 'Gibraltar', 'MOB', 'gib'),
(167, 'Globalstar', 'NGN', 'gs8'),
(168, 'Greece', 'FIX', 'grc'),
(169, 'Greece', 'MOB', 'grc'),
(170, 'Greenland', 'FIX', 'grl'),
(171, 'Greenland', 'MOB', 'grl'),
(172, 'Grenada', 'FIX', 'grd'),
(173, 'Grenada', 'MOB', 'grd'),
(174, 'Guadeloupe', 'FIX', 'glp'),
(175, 'Guadeloupe', 'MOB', 'glp'),
(176, 'Guam', 'FIX', 'gum'),
(177, 'Guatemala', 'FIX', 'gtm'),
(178, 'Guatemala', 'MOB', 'gtm'),
(179, 'Guinea', 'FIX', 'gin'),
(180, 'Guinea', 'MOB', 'gin'),
(181, 'Guinea-Bissau', 'FIX', 'gnb'),
(182, 'Guinea-Bissau', 'MOB', 'gnb'),
(183, 'Guyana', 'FIX', 'guy'),
(184, 'Guyana', 'MOB', 'guy'),
(185, 'Haiti', 'FIX', 'hti'),
(186, 'Haiti', 'MOB', 'hti'),
(187, 'Haiti', 'NGN', 'hti'),
(188, 'Honduras', 'FIX', 'hnd'),
(189, 'Honduras', 'MOB', 'hnd'),
(190, 'Hong Kong', 'FIX', 'hkg'),
(191, 'Hong Kong', 'MOB', 'hkg'),
(192, 'Hungary', 'FIX', 'hun'),
(193, 'Hungary', 'MOB', 'hun'),
(194, 'Iceland', 'FIX', 'isl'),
(195, 'Iceland', 'MOB', 'isl'),
(196, 'India', 'FIX', 'ind'),
(197, 'India', 'MOB', 'ind'),
(198, 'India', 'NGN', 'ind'),
(199, 'Indonesia', 'FIX', 'idn'),
(200, 'Indonesia', 'MOB', 'idn'),
(201, 'Inmarsat', 'NGN', 'xnm'),
(202, 'Iran', 'FIX', 'irn'),
(203, 'Iran', 'MOB', 'irn'),
(204, 'Iraq', 'FIX', 'irq'),
(205, 'Iraq', 'MOB', 'irq'),
(206, 'Ireland', 'FIX', 'irl'),
(207, 'Ireland', 'MOB', 'irl'),
(208, 'Ireland', 'NGN', 'irl'),
(209, 'Iridium', 'MOB', 'iri'),
(210, 'Israel', 'FIX', 'isr'),
(211, 'Israel', 'MOB', 'isr'),
(212, 'Israel', 'NGN', 'isr'),
(213, 'Italy', 'FIX', 'ita'),
(214, 'Italy', 'MOB', 'ita'),
(215, 'Italy', 'NGN', 'ita'),
(216, 'Jamaica', 'FIX', 'jam'),
(217, 'Jamaica', 'MOB', 'jam'),
(218, 'Japan', 'FIX', 'jpn'),
(219, 'Japan', 'MOB', 'jpn'),
(220, 'Jordan', 'FIX', 'jor'),
(221, 'Jordan', 'MOB', 'jor'),
(222, 'Kazakhstan', 'FIX', 'kaz'),
(223, 'Kazakhstan', 'MOB', 'kaz'),
(224, 'Kenya', 'FIX', 'ken'),
(225, 'Kenya', 'MOB', 'ken'),
(226, 'Kiribati', 'FIX', 'kir'),
(227, 'Kiribati', 'MOB', 'kir'),
(228, 'Korea, Democratic People''s Republic Of', 'FIX', 'prk'),
(229, 'Korea, Republic of', 'FIX', 'kor'),
(230, 'Korea, Republic of', 'MOB', 'kor'),
(231, 'Kuwait', 'FIX', 'kwt'),
(232, 'Kuwait', 'MOB', 'kwt'),
(233, 'Kyrgyzstan', 'FIX', 'kgz'),
(234, 'Kyrgyzstan', 'MOB', 'kgz'),
(235, 'Laos', 'FIX', 'lao'),
(236, 'Laos', 'MOB', 'lao'),
(237, 'Latvia', 'FIX', 'lva'),
(238, 'Latvia', 'MOB', 'lva'),
(239, 'Lebanon', 'FIX', 'lbn'),
(240, 'Lebanon', 'MOB', 'lbn'),
(241, 'Lesotho', 'FIX', 'lso'),
(242, 'Lesotho', 'MOB', 'lso'),
(243, 'Liberia', 'FIX', 'lbr'),
(244, 'Liberia', 'MOB', 'lbr'),
(245, 'Libyan Arab Jamahiriya', 'FIX', 'lby'),
(246, 'Libyan Arab Jamahiriya', 'MOB', 'lby'),
(247, 'Liechtenstein', 'FIX', 'lie'),
(248, 'Liechtenstein', 'MOB', 'lie'),
(249, 'Lithuania', 'FIX', 'ltu'),
(250, 'Lithuania', 'MOB', 'ltu'),
(251, 'Lithuania', 'NGN', 'ltu'),
(252, 'Luxembourg', 'FIX', 'lux'),
(253, 'Luxembourg', 'MOB', 'lux'),
(254, 'Macao', 'FIX', 'mac'),
(255, 'Macao', 'MOB', 'mac'),
(256, 'Macedonia', 'FIX', 'mkd'),
(257, 'Macedonia', 'MOB', 'mkd'),
(258, 'Madagascar', 'FIX', 'mdg'),
(259, 'Madagascar', 'MOB', 'mdg'),
(260, 'Malawi', 'FIX', 'mwi'),
(261, 'Malawi', 'MOB', 'mwi'),
(262, 'Malaysia', 'FIX', 'mys'),
(263, 'Malaysia', 'MOB', 'mys'),
(264, 'Maldives', 'FIX', 'mdv'),
(265, 'Maldives', 'MOB', 'mdv'),
(266, 'Mali', 'FIX', 'mli'),
(267, 'Mali', 'MOB', 'mli'),
(268, 'Malta', 'FIX', 'mlt'),
(269, 'Malta', 'MOB', 'mlt'),
(270, 'Marshall islands', 'FIX', 'mhl'),
(271, 'Martinique', 'FIX', 'mtq'),
(272, 'Martinique', 'MOB', 'mtq'),
(273, 'Mauritania', 'FIX', 'mrt'),
(274, 'Mauritania', 'MOB', 'mrt'),
(275, 'Mauritius', 'FIX', 'mus'),
(276, 'Mauritius', 'MOB', 'mus'),
(277, 'Mexico', 'FIX', 'mex'),
(278, 'Mexico', 'MOB', 'mex'),
(279, 'Micronesia', 'FIX', 'fsm'),
(280, 'Moldova', 'FIX', 'mda'),
(281, 'Moldova', 'MOB', 'mda'),
(282, 'Monaco', 'FIX', 'mco'),
(283, 'Monaco', 'MOB', 'mco'),
(284, 'Mongolia', 'FIX', 'mng'),
(285, 'Mongolia', 'MOB', 'mng'),
(286, 'Montserrat', 'FIX', 'msr'),
(287, 'Montserrat', 'MOB', 'msr'),
(288, 'Morocco', 'FIX', 'mar'),
(289, 'Morocco', 'MOB', 'mar'),
(290, 'Mozambique', 'FIX', 'moz'),
(291, 'Mozambique', 'MOB', 'moz'),
(292, 'Myanmar', 'FIX', 'mmr'),
(293, 'Myanmar', 'MOB', 'mmr'),
(294, 'Namibia', 'FIX', 'nam'),
(295, 'Namibia', 'MOB', 'nam'),
(296, 'Nauru', 'FIX', 'nru'),
(297, 'Nauru', 'MOB', 'nru'),
(298, 'Nepal', 'FIX', 'npl'),
(299, 'Nepal', 'MOB', 'npl'),
(300, 'Netherlands', 'FIX', 'nld'),
(301, 'Netherlands', 'MOB', 'nld'),
(302, 'Netherlands', 'NGN', 'nld'),
(303, 'Netherlands Antilles', 'FIX', 'ant'),
(304, 'Netherlands Antilles', 'MOB', 'ant'),
(305, 'New Caledonia', 'FIX', 'ncl'),
(306, 'New Caledonia', 'MOB', 'ncl'),
(307, 'New Zealand', 'FIX', 'nzl'),
(308, 'New Zealand', 'MOB', 'nzl'),
(309, 'Nicaragua', 'FIX', 'nic'),
(310, 'Nicaragua', 'MOB', 'nic'),
(311, 'Niger', 'FIX', 'ner'),
(312, 'Niger', 'MOB', 'ner'),
(313, 'Nigeria', 'FIX', 'nga'),
(314, 'Nigeria', 'MOB', 'nga'),
(315, 'Niue', 'FIX', 'niu'),
(316, 'Norfolk Island', 'FIX', 'nfk'),
(317, 'Norfolk Island', 'MOB', 'nfk'),
(318, 'Northern Mariana Islands', 'FIX', 'mnp'),
(320, 'Norway', 'FIX', 'nor'),
(321, 'Norway', 'MOB', 'nor'),
(322, 'Oman', 'FIX', 'omn'),
(323, 'Oman', 'MOB', 'omn'),
(324, 'Pakistan', 'FIX', 'pak'),
(325, 'Pakistan', 'MOB', 'pak'),
(326, 'Pakistan', 'NGN', 'pak'),
(327, 'Palau', 'FIX', 'plw'),
(328, 'Palestine', 'FIX', 'pse'),
(329, 'Palestine', 'MOB', 'pse'),
(330, 'Panama', 'FIX', 'pan'),
(331, 'Panama', 'MOB', 'pan'),
(332, 'Papua New Guinea', 'FIX', 'png'),
(333, 'Papua New Guinea', 'MOB', 'png'),
(334, 'Paraguay', 'FIX', 'pry'),
(335, 'Paraguay', 'MOB', 'pry'),
(336, 'Peru', 'FIX', 'per'),
(337, 'Peru', 'MOB', 'per'),
(338, 'Philippines', 'FIX', 'phl'),
(339, 'Philippines', 'MOB', 'phl'),
(340, 'Poland', 'FIX', 'pol'),
(341, 'Poland', 'MOB', 'pol'),
(342, 'Poland', 'NGN', 'pol'),
(343, 'Portugal', 'FIX', 'prt'),
(344, 'Portugal', 'MOB', 'prt'),
(345, 'Puerto Rico', 'FIX', 'pri'),
(346, 'Qatar', 'FIX', 'qat'),
(347, 'Qatar', 'MOB', 'qat'),
(348, 'Reunion', 'FIX', 'reu'),
(349, 'Reunion', 'MOB', 'reu'),
(350, 'Romania', 'FIX', 'rou'),
(351, 'Romania', 'MOB', 'rou'),
(352, 'Romania', 'NGN', 'rou'),
(353, 'Russian Federation', 'FIX', 'rus'),
(354, 'Russian Federation', 'MOB', 'rus'),
(355, 'Rwanda', 'FIX', 'rwa'),
(356, 'Rwanda', 'MOB', 'rwa'),
(357, 'Saint Helena', 'FIX', 'shn'),
(358, 'Saint Kitts And Nevis', 'FIX', 'kna'),
(359, 'Saint Kitts And Nevis', 'MOB', 'kna'),
(360, 'Saint Lucia', 'FIX', 'lca'),
(361, 'Saint Lucia', 'MOB', 'lca'),
(362, 'Saint Pierre And Miquelon', 'FIX', 'spm'),
(363, 'Saint Pierre And Miquelon', 'MOB', 'spm'),
(364, 'Saint Vincent And The Grenadines', 'FIX', 'vct'),
(365, 'Saint Vincent And The Grenadines', 'MOB', 'vct'),
(366, 'Samoa', 'FIX', 'wsm'),
(367, 'Samoa', 'MOB', 'wsm'),
(368, 'San Marino', 'FIX', 'smr'),
(369, 'San Marino', 'MOB', 'smr'),
(370, 'Sao Tome And Principe', 'FIX', 'stp'),
(371, 'Sao Tome And Principe', 'MOB', 'stp'),
(372, 'Saudi Arabia', 'FIX', 'sau'),
(374, 'Saudi Arabia', 'MOB', 'sau'),
(375, 'Senegal', 'FIX', 'sen'),
(376, 'Senegal', 'MOB', 'sen'),
(377, 'Serbia and Montenegro', 'FIX', 'scg'),
(378, 'Serbia and Montenegro', 'MOB', 'scg'),
(379, 'Seychelles', 'FIX', 'syc'),
(380, 'Seychelles', 'MOB', 'syc'),
(381, 'Sierra Leone', 'FIX', 'sle'),
(382, 'Sierra Leone', 'MOB', 'sle'),
(383, 'Singapore', 'FIX', 'sgp'),
(384, 'Singapore', 'MOB', 'sgp'),
(385, 'Slovakia', 'FIX', 'svk'),
(386, 'Slovakia', 'MOB', 'svk'),
(387, 'Slovenia', 'FIX', 'svn'),
(388, 'Slovenia', 'MOB', 'svn'),
(389, 'Solomon Islands', 'FIX', 'slb'),
(390, 'Solomon Islands', 'MOB', 'slb'),
(391, 'Somalia', 'FIX', 'som'),
(392, 'Somalia', 'MOB', 'som'),
(393, 'South Africa', 'FIX', 'zaf'),
(394, 'South Africa', 'MOB', 'zaf'),
(395, 'Spain', 'FIX', 'esp'),
(396, 'Spain', 'MOB', 'esp'),
(397, 'Spain', 'NGN', 'esp'),
(398, 'Sri Lanka', 'FIX', 'lka'),
(399, 'Sri Lanka', 'MOB', 'lka'),
(400, 'Sudan', 'FIX', 'sdn'),
(401, 'Sudan', 'MOB', 'sdn'),
(402, 'Suriname', 'FIX', 'sur'),
(403, 'Suriname', 'MOB', 'sur'),
(404, 'Swaziland', 'FIX', 'swz'),
(405, 'Swaziland', 'MOB', 'swz'),
(406, 'Sweden', 'FIX', 'swe'),
(407, 'Sweden', 'MOB', 'swe'),
(408, 'Sweden', 'NGN', 'swe'),
(409, 'Switzerland', 'FIX', 'che'),
(410, 'Switzerland', 'MOB', 'che'),
(411, 'Switzerland', 'NGN', 'che'),
(412, 'Syrian Arab Republic', 'FIX', 'syr'),
(413, 'Syrian Arab Republic', 'MOB', 'syr'),
(414, 'Taiwan', 'FIX', 'twn'),
(415, 'Taiwan', 'MOB', 'twn'),
(416, 'Tajikistan', 'FIX', 'tjk'),
(417, 'Tajikistan', 'MOB', 'tjk'),
(418, 'Tanzania', 'FIX', 'tza'),
(419, 'Tanzania', 'MOB', 'tza'),
(420, 'Thailand', 'FIX', 'tha'),
(421, 'Thailand', 'MOB', 'tha'),
(422, 'Togo', 'FIX', 'tgo'),
(423, 'Togo', 'MOB', 'tgo'),
(424, 'Tokelau', 'FIX', 'tkl'),
(425, 'Tonga', 'FIX', 'ton'),
(426, 'Tonga', 'MOB', 'ton'),
(427, 'Trinidad And Tobago', 'FIX', 'tto'),
(428, 'Trinidad And Tobago', 'MOB', 'tto'),
(429, 'Tunisia', 'FIX', 'tun'),
(430, 'Tunisia', 'MOB', 'tun'),
(431, 'Turkey', 'FIX', 'tur'),
(432, 'Turkey', 'MOB', 'tur'),
(433, 'Turkmenistan', 'FIX', 'tkm'),
(434, 'Turkmenistan', 'MOB', 'tkm'),
(435, 'Turks And Caicos Islands', 'FIX', 'tca'),
(436, 'Turks And Caicos Islands', 'MOB', 'tca'),
(437, 'Tuvalu', 'FIX', 'tuv'),
(438, 'Tuvalu', 'MOB', 'tuv'),
(439, 'Uganda', 'FIX', 'uga'),
(440, 'Uganda', 'MOB', 'uga'),
(441, 'Ukraine', 'FIX', 'ukr'),
(442, 'Ukraine', 'MOB', 'ukr'),
(443, 'United Arab Emirates', 'FIX', 'are'),
(444, 'United Arab Emirates', 'MOB', 'are'),
(445, 'United Kingdom', 'FIX', 'gbr'),
(446, 'United Kingdom', 'MOB', 'gbr'),
(447, 'United Kingdom', 'NGN', 'gbr'),
(448, 'United States', 'FIX', 'usa'),
(449, 'United States', 'NGN', 'usa'),
(450, 'Uruguay', 'FIX', 'ury'),
(451, 'Uruguay', 'MOB', 'ury'),
(452, 'Uzbekistan', 'FIX', 'uzb'),
(453, 'Uzbekistan', 'MOB', 'uzb'),
(454, 'Vanuatu', 'FIX', 'vut'),
(455, 'Vanuatu', 'MOB', 'vut'),
(456, 'Vatican City', 'FIX', 'vat'),
(457, 'Vatican City', 'MOB', 'vat'),
(458, 'Venezuela', 'FIX', 'ven'),
(459, 'Venezuela', 'MOB', 'ven'),
(460, 'Vietnam', 'FIX', 'vnm'),
(461, 'Vietnam', 'MOB', 'vnm'),
(462, 'Virgin Islands, British', 'FIX', 'vgb'),
(463, 'Virgin Islands, U.S.', 'FIX', 'vir'),
(464, 'Wallis And Futuna', 'FIX', 'wlf'),
(465, 'Yemen', 'FIX', 'yem'),
(466, 'Yemen', 'MOB', 'yem'),
(467, 'Zambia', 'FIX', 'zmb'),
(468, 'Zambia', 'MOB', 'zmb'),
(469, 'Zimbabwe', 'FIX', 'zwe'),
(470, 'Zimbabwe', 'MOB', 'zwe'),
(471, 'Montenegro', 'FIX', 'mbx'),
(472, 'Montenegro', 'MOB', 'mbx'),
(473, 'Afghanistan', 'NGN', 'afg'),
(474, 'Algeria', 'NGN', 'dza'),
(475, 'Anguilla', 'NGN', 'aia'),
(476, 'Antigua And Barbuda', 'NGN', 'atg'),
(477, 'Armenia', 'NGN', 'arm'),
(478, 'Australia', 'NGN', 'aus'),
(480, 'Belize', 'NGN', 'blz'),
(481, 'Benin', 'NGN', 'ben'),
(482, 'Bolivia', 'NGN', 'bol'),
(483, 'Bosnia And Herzegovina', 'NGN', 'bih'),
(484, 'Brunei Darussalam', 'NGN', 'brn'),
(485, 'Bulgaria', 'NGN', 'bgr'),
(486, 'Central African Republic', 'MOB', 'caf'),
(487, 'Chile', 'NGN', 'chl'),
(488, 'Czech Republic', 'NGN', 'cze'),
(489, 'Congo, The Democratic Republic Of The', 'NGN', 'cod'),
(490, 'Cuba', 'MOB', 'cub'),
(491, 'Colombia', 'NGN', 'col'),
(492, 'Comoros', 'NGN', 'com'),
(493, 'Congo', 'NGN', 'cog'),
(494, 'Cook Islands', 'NGN', 'cok'),
(495, 'Diego Garcia', 'NGN', 'dga'),
(496, 'Dominica', 'NGN', 'dma'),
(497, 'Dominican Republic', 'NGN', 'dom'),
(498, 'East Timor', 'NGN', 'tmp'),
(499, 'Egypt', 'NGN', 'egy'),
(500, 'Estonia', 'NGN', 'est'),
(501, 'Eritrea', 'MOB', 'eri'),
(502, 'Eurosat Satellite', 'NGN', 'eus'),
(503, 'Falkland Islands (Malvinas)', 'MOB', 'flk'),
(504, 'Faroe Islands', 'NGN', 'fro'),
(505, 'Fiji', 'NGN', 'fji'),
(506, 'Gambia', 'NGN', 'gmb'),
(507, 'Georgia', 'NGN', 'geo'),
(508, 'Guyana', 'NGN', 'guy'),
(509, 'Gibraltar', 'NGN', 'gib'),
(510, 'Greece', 'NGN', 'grc'),
(511, 'Guinea-Bissau', 'NGN', 'gnb'),
(512, 'Garuda Satellite', 'NGN', 'gas'),
(513, 'Global Communications', 'NGN', 'ico'),
(514, 'Hong Kong', 'NGN', 'hkg'),
(515, 'Hungary', 'NGN', 'hun'),
(516, 'Iceland', 'NGN', 'isl'),
(517, 'Indonesia', 'NGN', 'idn'),
(518, 'Ivory Coast', 'NGN', 'civ'),
(519, 'Jamaica', 'NGN', 'jam'),
(520, 'Japan', 'NGN', 'jpn'),
(521, 'Jordan', 'NGN', 'jor'),
(522, 'Kenya', 'NGN', 'ken'),
(523, 'Korea, Republic of', 'NGN', 'kor'),
(524, 'Kosovo', 'FIX', 'kos'),
(525, 'Kosovo', 'MOB', 'kos'),
(526, 'Kuwait', 'NGN', 'kwt'),
(527, 'Latvia', 'NGN', 'lva'),
(528, 'Lebanon', 'NGN', 'lbn'),
(529, 'Lesotho', 'NGN', 'lso'),
(530, 'Liechtenstein', 'NGN', 'lie'),
(531, 'Luxembourg', 'NGN', 'lux'),
(532, 'Macedonia', 'NGN', 'mkd'),
(533, 'Madagascar', 'NGN', 'mdg'),
(534, 'Maldives', 'NGN', 'mdv'),
(535, 'Malta', 'NGN', 'mlt'),
(536, 'Marshall islands', 'MOB', 'mhl'),
(537, 'Mauritius', 'NGN', 'mus'),
(538, 'Mayotte', 'FIX', 'myt'),
(539, 'Mayotte', 'MOB', 'myt'),
(540, 'Micronesia', 'MOB', 'fsm'),
(541, 'Moldova', 'NGN', 'mda'),
(542, 'Monaco', 'NGN', 'mco'),
(543, 'Montserrat', 'NGN', 'msr'),
(544, 'Morocco', 'NGN', 'mar'),
(545, 'Mozambique', 'NGN', 'moz'),
(546, 'Midway island', 'FIX', 'mid'),
(547, 'Nauru', 'NGN', 'nru'),
(548, 'Netherlands Antilles', 'NGN', 'ant'),
(549, 'Nicaragua', 'NGN', 'nic'),
(550, 'Norway', 'NGN', 'nor'),
(551, 'New Caledonia', 'NGN', 'ncl'),
(552, 'New Zealand', 'NGN', 'nzl'),
(553, 'Niue', 'NGN', 'niu'),
(554, 'Norfolk Island', 'NGN', 'nfk'),
(555, 'Northern Mariana Islands', 'MOB', 'mnp'),
(556, 'Oman', 'NGN', 'omn'),
(557, 'Palau', 'MOB', 'plw'),
(558, 'Philippines', 'NGN', 'phl'),
(559, 'Portugal', 'NGN', 'prt'),
(560, 'Papua New Guinea', 'NGN', 'png'),
(561, 'Paraguay', 'NGN', 'pry'),
(562, 'Qatar', 'NGN', 'qat'),
(563, 'Russian Federation', 'NGN', 'rus'),
(564, 'Saint Helena', 'NGN', 'shn'),
(565, 'Senegal', 'NGN', 'sen'),
(566, 'Slovakia', 'NGN', 'svk'),
(567, 'Slovenia', 'NGN', 'svn'),
(568, 'Samoa', 'NGN', 'wsm'),
(569, 'South Africa', 'NGN', 'zaf'),
(570, 'Suriname', 'NGN', 'sur'),
(571, 'Taiwan', 'NGN', 'twn'),
(572, 'Tanzania', 'NGN', 'tza'),
(573, 'Thuraja', 'NGN', 'thu'),
(574, 'Tunisia', 'NGN', 'tun'),
(575, 'Turkey', 'NGN', 'tur'),
(576, 'Turks And Caicos Islands', 'NGN', 'tca'),
(577, 'Tokelau', 'NGN', 'tkl'),
(578, 'Tuvalu', 'NGN', 'tuv'),
(579, 'Ukraine', 'NGN', 'ukr'),
(580, 'Vanuatu', 'NGN', 'vut'),
(581, 'Virgin Islands, British', 'MOB', 'vgb'),
(582, 'Seychelles', 'NGN', 'syc');
