
DROP DATABASE IF EXISTS mor;

CREATE DATABASE mor CHARACTER SET utf8;

GRANT ALL PRIVILEGES ON mor.* TO mor@localhost IDENTIFIED BY "mor" WITH GRANT OPTION;
GRANT PROCESS, SUPER, FILE, REPLICATION SLAVE , REPLICATION CLIENT ON * . * TO 'mor'@'localhost';

USE mor;
